### ISSUE TITLE
Filter "Downloaded Episodes" is not working

### ISSUE THREAD

**Issue by peter099** [gpodder/gpodder#1199]
If i understand correctly when i press Ctrl+2 it should show only the downloaded episodes and hide all other episodes, but this is not happening. I am using gPodder version 3.10.20 on MX Linux.

**Comment by auouymous** [comment]
Ctrl+2 shows downloaded episodes **and** undownloaded episodes that are marked as new. It allows you to be able to download those new episodes instead of hiding them and making download impossible. When combined with the filter extension, ctrl+2 automatically hides "new" episodes you don't want to see.

Ctrl+3 is the only option that might not be viable for everyday use since it immediately hides the episode when you start playing it.

**Comment by peter099** [comment]
Yes, the option "Always show New Episodes" was checked. If i uncheck it, then it shows only the downloaded episodes. Thanks.
