### ISSUE TITLE
mager! bug when syncing podcasts to device

### ISSUE THREAD

**Issue by mhussaincov93** [gpodder/gpodder#1230]
hi there,
not sure how to explain this but here goes.
I have a podcast that is radio programmes catchup, they split there mp3 files for every hour.
when syncing to my device, only the first mp3 file is synced the other mp3 files are not.
here's an exammple of what I mean.

2022-01-31 - Drivetime Monday 31 January.mp3
2022-01-31 - Drivetime Monday 31 January (2).mp3

when I look on the destination device, the only file of that programme that is synced is
2022-01-31 - Drivetime Monday 31 January.mp3
attached will be my settings.json file.
stepps to reproduce:
1.
subscribe to this podcast.
https://podcast.canstream.co.uk/wcrfm/podcast.php
2.
download hour one and hour 2 of a programme.
3.
sync to a device.
what should happen
all files should be synced 
what happens
only the first file is synced.
thanks for your help
Majid
[Settings.json.zip](https://github.com/gpodder/gpodder/files/8056555/Settings.json.zip)

**Comment by auouymous** [comment]
The problem is that gpodder uses the title when syncing files, and that feed uses the same title for each part, causing them to overwrite each other. The device would display episodes as `wcrfm_08-02-22_2-2_1644285601.mp3` instead of `The No Repeat Nightshift Tuesday 8 February.mp3`, if gpodder wrote the enclosure filename instead of title.

Checking `device_sync.custom_sync_name_enabled` and changing `device_sync.custom_sync_name` to `{episode.download_filename}` does that, except that it causes the file extension to appear twice: `wcrfm_08-02-22_2-2_1644285601.mp3.mp3`.

Using `{episode.title}_{episode.id}` appends gpodder's ID to the end, which is unique, but you might want to distinguish it as an ID with something like `{episode.title} [ID: {episode.id}]`. You won't know which hour each episode is, but higher IDs will likely map to higher hours. And prefix with `{episode.sortdate}_` if you want that in the filenames.

Or contact the feed author and ask them to append the hour to each title in the feed.
