### ISSUE TITLE
Question how to find not longer downloadable youtube channels

### ISSUE THREAD

**Issue by computerfreak105** [gpodder/gpodder#1240]
Hello all, I have about a hundred youtube channels I'm monitoring with Gpodder on Windows. Now wich each download I can hear my screen reader telling me
that two channels can't be downloaded. I guess these got closed for some reason. Now I'd like to find these and remove them from my subs. I tried to search
in the GPO log files. But these are loaded full with errors so I'm a bit lost for what to search exactly. Is there a specific keyword I could search for
in order to get to a channel wich can't be downloaded anymore quickly?
Or could GPO be made to eject such channels automatically, if desired?

Thanks
Ben

**Comment by auouymous** [comment]
When updating with gpo the following line is displayed after the wall of errors.

```
 test feed                                                               [FAIL]
```

A successful update shows `[DONE]` instead of `[FAIL]`, but nothing is put in the log.

`gpo update 2>/dev/null` on linux gets rid of the exceptions and might be more useful for you. And stackoverflow suggests `gpo update 2> nul` does the same on windows.

Automatically removing failed channels would be bad if one of your channels was down for a few minutes during your update.

**Comment by computerfreak105** [comment]
There doesn't seem to exist such a command:
> gpo update 2> nul
> 


on Windows 10. It says the requested function is not available. Removing the gpo says wrong argument for update.
But thanks for your suggestion. For now I just do a normal update in GPO and then copy the terminal content. then I paste it into a text editor to read.
But I'm still interested in this command which would have no entry in the logs. So, if the correct syntax got lost in the mail, please let me know. I didn't find the post on stackoverflow so far.

**Comment by auouymous** [comment]
Oops, you might need to append `.exe` to it on windows, so run `gpo.exe update 2> nul`. It is just the normal gpo update command you use, but with `2> nul` added on the end.

**Comment by computerfreak105** [comment]
no problem, works like a charm now, thanks.
