### ISSUE TITLE
question/ possible? sample rate and setting mono instead of Stereo when converting to opus

### ISSUE THREAD

**Issue by mhussaincov93** [gpodder/gpodder#1257]
hi,
sorry if the subject line is not that informative.
is it possible to set the sample rate along with the files mono /Stereo for audio files output?
at the moment i've got to use an external audio converter with the folowing settings.
the .opus codec
16 kbps
mono
sample rate 48000
i'm guessing that ffmpeg is being used?
what would I need to change in audio_converter.py?
thank you for your assistence :)
Majid

**Comment by auouymous** [comment]
Change

'.opus': ['-n', '-i', '%(old_file)s', '-b:a', '64k', '%(new_file)s']

to

'.opus': ['-n', '-i', '%(old_file)s', **'-ac', '1', '-ar', '48k',** '-b:a', '**16k**', '%(new_file)s']

There are two of these lines, one for avconv and one for ffmpeg, set the correct one depending on which program you have installed, or change both if you don't know.

**Comment by mhussaincov93** [comment]
my eternal thanks!
instead of changeing the main audio convert file that is located in the install dir of gpodder is there a local place in the user's directory where these changes could be made?
if yes could someone tell me?
seembs risky to alter installed files like this.
going to test your command line sir,
had a hdd faile with 3tb of podcasts collected over 3 years.
cons data loss mager,
pros fresh start, with output settings correctly set space saveings etc.
*sigh*
thank you for your help sir :)
pardon my spelling errors I use assistive tech

**Comment by mhussaincov93** [comment]
[audio_converter.py.zip](https://github.com/gpodder/gpodder/files/8341530/audio_converter.py.zip)
hi,
not sure if i've got that write if it is possible, could you take a look for me and if in error change it for me?
since I can't see indentation due to being blind it's a guessing game.
Majid

**Comment by mhussaincov93** [comment]
information:
i'm using ffmpeg.

**Comment by auouymous** [comment]
You can add your own extensions in ~/gPodder/Extensions/, create that directory if it doesn't already exist. I don't know if it will work, but you can try copying the extension there, modifying it, and see if gpodder chooses it over the installed version. Or just copy the extension there, rename it to my_audio_converter.py and tell gpodder to use it instead of the installed extension.

If you rename it, you should modify this line so you can distinguish the two extensions.

```
__title__ = _('Convert audio files')
```

The avconv line is correct but you messed up the ffmpeg line, there is a double `'` before `-ac`.

**Comment by mhussaincov93** [comment]
my thanks!
it all works now!
thank you for your teaching teacher auouymous
space saveings for the win!
Majid
