### ISSUE TITLE
gpodder shows "no new episodes" for Freakonomics

### ISSUE THREAD

**Issue by SpikedCola** [gpodder/gpodder#1271]
The url to the feed is: https://freakonomics.com/series/freakonomics-radio/feed/

When I add it to gpodder, the name and description are shown in gpodder, but it only shows "no new episodes", even after manually checking for updates. If I visit the feed in a browser, I can see recent episodes that should be downloaded.

I am using the latest version, 3.20.21, on Windows 7. Please let me know if I can provide any additional debugging information.

**Comment by auouymous** [comment]
The problem is that feed lacks enclosures (downloadable content) and gpodder ignores episodes without them. It would be better if gpodder displayed the episodes and then displayed an error when you attempted to download them, because then you would know there is no content. In the case of that feed, you could click the episode title in shownotes and access the content in your web browser. Or if the feed was popular, someone could add support to gpodder so it could query the webpage and download the content like happens with youtube.

**Comment by Ryochan7** [comment]
Here is the actual Podcast feed 

https://feeds.simplecast.com/Y8lFbOT4

**Comment by SpikedCola** [comment]
@Ryochan7 Thanks for the correct link! Appreciate it.
@auouymous it might help if there was an obvious error message displayed, I didn't even notice I only had a "post" xml feed, and not a podcast feed, because it partly worked. But this is totally on me though! It's easily worked around by using the correct link.

**Comment by auouymous** [comment]
I created PR #1272 to not only fix issues like this were nothing appears, but also for subscribing to RSS feeds with no media or media only available on a webpage.
