### ISSUE TITLE
TypeError: Argument 1 does not allow None as a value

### ISSUE THREAD

**Issue by blokdk** [gpodder/gpodder#1275]
"_TypeError: Argument 1 does not allow None as a value_" is what I see several times when I look at the log. 
This morning I finally got round to installing the git version of gPodder on my raspi3B in the spot where I want it. 
It sees my older downloaded podcasts, even lets me download new episodes.

But it does not show an icon indicating they can be played; the older ones do have the icon. The newly downloaded are shown with their names in **Bold**. There are no options if I right click the episode. 

Please advise

**Comment by auouymous** [comment]
Could you please post the full stack trace before that error in the log?

**Comment by blokdk** [comment]
2022-04-15 18:13:13,289 [gpodder.log] ERROR: Uncaught exception: Traceback (most recent call last):
  File "/media/FTP/files/Podcasts/gPodder/gpodder/src/gpodder/gtkui/main.py", line 1032, in on_episode_list_selection_changed
    self.play_or_download()
  File "/media/FTP/files/Podcasts/gPodder/gpodder/src/gpodder/gtkui/main.py", line 2279, in play_or_download
    self.set_episode_actions(open_instead_of_play, can_play, can_download, can_pause, can_cancel, can_delete)
  File "/media/FTP/files/Podcasts/gPodder/gpodder/src/gpodder/gtkui/main.py", line 2101, in set_episode_actions
    self.toolPause.set_sensitive(can_pause)
TypeError: Argument 1 does not allow None as a value

**Comment by auouymous** [comment]
Do you have an older version of gpodder installed elsewhere on that device? `share/gpodder/ui/gtk/gpodder.ui` added a new toolPause button but is outside the `src` directory. You might be using the older /usr/share/gpodder directory instead of the share directory in the git repo.

**Comment by blokdk** [comment]
Thanks, you were so right in your diagnosis. ;-)

Running fine now!

**Comment by computerfreak105** [comment]
Hello all

I remember some recent posts here which declare problems with youtube-dl. And I thought, why not switch to another program which still gets updated?

https://github.com/yt-dlp/yt-dlp

However, if there will be a change, I really wish all users could have the ability to update it by themself whenever the need arrises. Couldn't yt-dlp or whatever it will be integrated in such a way into GPO so that it's placed in a dedicated folder wherever one can just issue the update command from CLI or copy the latest version to this folder? We already have a youtube-dl folder, but it just contains a youtube-sigfuncs folder and then some .json files.

Thanks for considering
Ben

**Comment by auouymous** [comment]
This issue has nothing to do with youtube-dl, and yt-dlp is already used by gpodder. Linux users can update their youtube-dl or yt-dlp outside of gpodder, but we haven't implemented that ability for Mac and Windows users yet.
