### ISSUE TITLE
Feature Request: Use yt-dlp instead of youtube-dl

### ISSUE THREAD

**Issue by computerfreak105** [gpodder/gpodder#1283]
Hello all

I remember some recent posts here which declare problems with youtube-dl. And I thought, why not switch to another program which still is updated regularly?

https://github.com/yt-dlp/yt-dlp

However, if there will be a change, I really wish all users could have the ability to update it by themself whenever the need arrises. Couldn't yt-dlp or whatever it will be integrated in such a way into GPO so that it's placed in a dedicated folder wherever one can just issue the update command from CLI or copy the latest version to this folder? We already have a youtube-dl folder, but it just contains a youtube-sigfuncs folder and then some .json files.

Thanks for considering
Ben

**Comment by auouymous** [comment]
gpodder has used yt-dlp by default since #1182. Linux users can upgrade yt-dlp from their distribution. Mac and Windows users must wait for new releases to get yt-dlp updates, however, Windows users can upgrade to git artifacts (https://ci.appveyor.com/project/elelay/gpodder/build/artifacts) to access development versions of gpodder and newer releases of yt-dlp.

There was work a while back to allow Windows and Mac users to update youtube-dl but it hasn't been completed yet.

**Comment by tpikonen** [comment]
Version 3.11.0 has now been released with yt-dlp, so closing this.

**Comment by computerfreak105** [comment]
Thanks, I updated with the git artifact.
Do I need to configure Gpodder to use yt-dlp in the settings file or does it happen anyway?

**Comment by auouymous** [comment]
It will be automatic, assuming you had the youtube-dl extension enabled before. The extension is still called youtube-dl, but it is using yt-dlp.
