### ISSUE TITLE
Perhaps download as html non media data in channel/feeds

### ISSUE THREAD

**Issue by Snippet24816** [gpodder/gpodder#1410]
Just an idea perhaps a bad one, but would be great if database info such as descriptions/details text for each episode would be saved (so far they only live in the database I assume) but if older episodes are cleaned/removed this data would be gone I guess.

**Comment by auouymous** [comment]
Gpodder will store episode information for downloaded episodes forever, until you delete the downloaded file. But episodes that aren't currently downloaded get removed from the database, if no longer in the feed.

An option could be added to not remove old episodes. However, it might lead to issues, such as the feed site no longer hosting the episode files or changing CDNs. There are cases like youtube where the feed only contains the 15 most recent episodes even though old episodes are available forever unless removed by youtube or the creator.

Another problem is the episode limit setting which tells gpodder to only keep the newest N episodes in the database, ignoring older downloaded episodes. If it is set to 10 and the feed removes one of the 10 newest, and re-adds the 11th episode back in the feed, gpodder will keep that removed invalid episode and not re-add the 11th valid episode.

Is this what you are asking for?

**Comment by tomasts248** [comment]
> Gpodder will store episode information for downloaded episodes forever, until you delete the downloaded file. But episodes that aren't currently downloaded get removed from the database, if no longer in the feed.

Great :+1: 

Okey I have a question in my ignorance: would storing the episode information in a file next to a downloaded video/audio instead of inside the database make the database smaller? But I suppose it would be slower the load of any episode detail/information?

Thank you so much for explaining!!  :)

**Comment by Snippet24816** [comment]
> Gpodder will store episode information for downloaded episodes forever, until you delete the downloaded file. But episodes that aren't currently downloaded get removed from the database, if no longer in the feed.

Great :+1: 

Okey I have a question in my ignorance: would storing the episode information in a file next to a downloaded video/audio instead of inside the database make the database smaller? But I suppose it would be slower the load of any episode detail/information?

Thank you so much for explaining!!  :)

**Comment by auouymous** [comment]
Correct, the database would get smaller, but gpodder would be too slow to use.

**Comment by Snippet24816** [comment]
Understood!

**Comment by Snippet24816** [comment]
I have been giving some seconds thoughts to this, there's a scenario where it would be useful: to make the data available to other applications as well.
Else I did some experiment, and subscribed to a regular RSS feed, and worked fine except it didn't load the images.
Would it be bad idea to have say a plugin to store regular feeds as an html file? that way images are stored and can be viewed?

**Comment by auouymous** [comment]
Feeds have a text description or html description. If you have webkit (not in the windows or mac builds), the shownotes will display an html description with links and images. Those with text shownotes get html descriptions that have been de-htmlified and then any links are highlighted. For feeds with only text descriptions, both text and html shownote users get the same description with links highlighted.

Downloading the description to an html file or converting text description to html makes sense for anyone who will reading while offline. However, gpodder would then need to spider the description and download all assets (images, audio, video, javascript, css), or they would not be available when offline. Simply storing to an html file won't cut it when you can just as easily click the title in shownotes to open the episode in a browser.

Users with text shownotes (anyone without webkit) can not view the downloaded html+assets, and gpodder would need to open it in a browser.

This would need to be part of the download system. Any episode with an html description and no enclosure could be downloadable. Downloading would spider the description and somehow save everything to a single file (archive), otherwise startup would complain about unknown external files. The assets in this file would somehow become available to webkit shownotes, and opening the file would somehow load the archive into a web browser. So if anyone wants to figure that out and implement it...

**Comment by Snippet24816** [comment]
I understand thanks for expalaining :)

> Downloading the description to an html file or converting text description to html makes sense for anyone who will reading while offline. 

I do fear at some point the blogs I love would be gone..

> So if anyone wants to figure that out and implement it...

What about this? https://github.com/gildas-lormeau/SingleFile
it has a cli version as well.

**Comment by auouymous** [comment]
I know images can be base64 encoded and stored in the html file because I do it on my own sites for small non-content images. I assume the same could be done for audio and video elements, but those are much larger files and encoding would increase the content size by 33%. It could still be a very useful feature if someone has the time to implement it, and could be done as an extension if third-party dependencies are needed to do the encoding. That SingleFile project would however require a massive `node` dependency and would not be bundled in the windows or mac versions of gpodder.

**Comment by Snippet24816** [comment]
> That SingleFile project would however require a massive node dependency and would not be bundled in the windows or mac versions of gpodder.
Understood. I will mention this just in case: there's another option to save a webpage in a single file: MHTML format. Looking around found a script for it https://stackoverflow.com/questions/995339/saving-webpage-as-mhtm-file
Perhaps is useful most likely not..

**Comment by Snippet24816** [comment]
What do you think about it?

**Comment by auouymous** [comment]
> What do you think about it?

https://stackoverflow.com/questions/995339/saving-webpage-as-mhtm-file is a Windows only solution.

**Comment by Snippet24816** [comment]
> is a Windows only solution.

I'm out of ideas :(

**Comment by auouymous** [comment]
Embedding the content in an html file is very easy to do. Finding someone with the time to implement the feature is harder.

**Comment by Snippet24816** [comment]
I see.. wish I could help

**Comment by Snippet24816** [comment]
I have an idea, what about storing html contents as an epub file?
Idea while I was reading this:
https://github.com/koreader/koreader/issues/9249
