### ISSUE TITLE
Settings.json getting changed upon reboot.

### ISSUE THREAD

**Issue by Needabrew** [gpodder/gpodder#1417]
About 75% of the times I reboot my machine, Settings.json gets changed the x and y locations get changed to -3200 as shown in the snippet below:

        "main_window": {
          "episode_column_order": [],
          "episode_column_sort_id": 12,
          "episode_column_sort_order": false,
          "episode_list_size": 509,
          "height": 635,
          "maximized": false,
          "paned_position": 280,
          "width": 1100,
          "x": -32000,
          "y": -32000
        },

The correct values are -1 as shown below. I have to manually edit the Settings.json file way to often.  Not sure if this is a bug, or just me. Bringing it up just in case it's a bug. 

        "main_window": {
          "episode_column_order": [],
          "episode_column_sort_id": 12,
          "episode_column_sort_order": false,
          "episode_list_size": 509,
          "height": 635,
          "maximized": false,
          "paned_position": 280,
          "width": 1100,
          "x": -1,
          "y": -1
        },

I am running Windows 11 pro version 22H2 did the same with the previous version also.  
gPodder 3.11.0 (2022-07-30)

I will try shutting down gpodder before rebooting and see if that helps.  Normally it is on 24x7 and don't pay that much attention to it.

Cheers!

**Comment by auouymous** [comment]
Do you have any kind of virtual desktops? Gpodder remembers the position of windows when they are closed, and closing a window while it is on another desktop area causes negative or excessively positive values.

This was fixed by #1356 and available at https://ci.appveyor.com/project/elelay/gpodder/build/artifacts if you want to use current git, or you'll need to wait for the next release.
