### ISSUE TITLE
gPodder macOS build for 3.9.1

### ISSUE THREAD

**Issue by popstas** [gpodder/gpodder#142]
It shows:

```
New version available

Installed version: 3.9.0
Newest version: 3.9.1
Release date: 2016-08-31

Download the latest version from gpodder.org?
```

But at http://gpodder.org/downloads there is no 3.9.1 version for Mac, only 3.9.0

**Comment by thp** [comment]
Yes, it might take a while for @elelay to update the macOS build. Check back in a few days :)

Reason why the update checker shows the new version is because it just checks for the new upstream (= source code) version of gPodder, not the particular builds, we might want to change that in the future to

**Comment by elelay** [comment]
Yeah, I'm slacking...
To be honest I'm not too fond of the webkit rendering drop.
I'll release next week if all goes according to the plan (I'll do a full rebuild without the webkit deps and with the new html5lib).

**Comment by thp** [comment]
@elelay Hm, would it make sense to revert the webkit drop commit and allow it optional for e.g. the OS X build? We removed it mostly because it was deprecated on Debian, but I'm happy to add it back if you think it's better with it.

**Comment by elelay** [comment]
@thp why not indeed, maybe a branch? Or I could include the revert patch in the build.
By the way, any progress on gtk3/webkit2?

**Comment by popstas** [comment]
Still 3.9.0_1 on download page.

**Comment by popstas** [comment]
Got 3.9.1, thank you.
