### ISSUE TITLE
Feed shows no epsiodes - other feed from same source does

### ISSUE THREAD

**Issue by hayguen** [gpodder/gpodder#1445]
this feed doesn't show any episode - but i also get no error message:
* https://rmrc.de/index.php/component/podcastmanager/?format=raw&feedname=3

other feeds - from the same source - work without problems, e.g.:
* https://rmrc.de/index.php/component/podcastmanager/?format=raw&feedname=1
* https://rmrc.de/index.php/component/podcastmanager/?format=raw&feedname=2

i'm new to gPodder and this problem occurs on windows with the Portable download of today:
gPodder 3.11.0 (2022-07-30)

any idea?
is it possible to get an error message/log file?

**Comment by hayguen** [comment]
on suspicion, i renamed the mp3 filename (enclosure url) .. and replaced the spaces by underscore.
that helped.

sure, space in the filename are no good idea .. but means, that gPodder has a problem with spaces in the filename.

**Comment by auouymous** [comment]
https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Frmrc.de%2Findex.php%2Fcomponent%2Fpodcastmanager%2F%3Fformat%3Draw%26feedname%3D3

The feed uses spaces in URLs for every episode and gpodder discards all of them because URLs are not allowed to contain spaces. I just pushed 3 commits to show the episodes, show an error icon and not try to download them when subscribing. You can update gpodder to the artifacts on https://ci.appveyor.com/project/elelay/gpodder/builds/45692621 in an hour when it has finished building. But you'll need to contact the feed author to get the problem fixed.

**Comment by hayguen** [comment]
@auouymous : unfortunately, the feed author (webmaster) is me .. 
i simply put those files including spaces online, i had received via email.
meanwhile renamed the latest 4 episodes .. and left the older ones.
there are few listeners of this feed .. but i got no problem report. and this feed exists for multiple years.

technically, you are right for not downloading .. but compared to other podcast apps (AntennaPod does download and play without any warning), i would suggest to do it in a similar way: if necessary, replace spaces with the urlencoded chars .. but simply download and play those erroneous files.

**Comment by auouymous** [comment]
There is nothing wrong with spaces in the filenames. You simply need to encode them as `%20` or `+` in the feed URLs. Gpodder will then download them and the local files will have spaces.

Unlike other clients, we have a policy to not support feeds that violate specifications.
