### ISSUE TITLE
gpodder/?? on windows unable to set sync directory blind user here.

### ISSUE THREAD

**Issue by mhussaincov93** [gpodder/gpodder#1493]
hi,
i'm blind and am now on windows for reasons beond my control.
my screen reader nvda and gpodder-gtk do not work at all.
due to this, I am unable to choose my new sync directory for podcasts.
editing settings.json does nothing, my changes get revirted.
if this could be fixed I would be greatful.
my podcast sync dir is
f:\lps\.
here's what I put in settings.json.
    "device_folder": "f:\lps\",
    "device_type": "filesystem",
that last line getts changed to
    "device_type": "none",
after gpo has ran and i've tryed async.
I would be greatful if someone could look in to this for me.
Majid

**Comment by computerfreak105** [comment]
Hi, I’m blind as well. Unfortunately I don’t have a solution for you, because I never sync podcasts. I use GPodder only for youtube channels.

But out of interest, did you find a solution yet? How did you manage it before using windows?

 

 

 

 

 

 

Von: mhussaincov93 ***@***.***> 
Gesendet: Mittwoch, 15. März 2023 09:07
An: gpodder/gpodder ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [gpodder/gpodder] gpodder/?? on windows unable to set sync directory blind user here. (Issue #1493)

 

hi,
i'm blind and am now on windows for reasons beond my control.
my screen reader nvda and gpodder-gtk do not work at all.
due to this, I am unable to choose my new sync directory for podcasts.
editing settings.json does nothing, my changes get revirted.
if this could be fixed I would be greatful.
my podcast sync dir is
f:\lps.
here's what I put in settings.json.
"device_folder": "f:\lps",
"device_type": "filesystem",
that last line getts changed to
"device_type": "none",
after gpo has ran and i've tryed async.
I would be greatful if someone could look in to this for me.
Majid

**Comment by mhussaincov93** [comment]
hi,
in linux land, the ui is accessible.
away around this would be
if gpodder detects that a sync dir is not set, launch a native open with window from explorer which should be accessible to set the directory.
is this possible?

**Comment by auouymous** [comment]
I don't see any code that would change `device_type`. I think if you made a mistake editing the settings file it would revert the entire file, but `device_folder` and other settings do not get reverted?

> if gpodder detects that a sync dir is not set, launch a native open with window from explorer which should be accessible to set the directory.

No it isn't possible.

**Comment by mhussaincov93** [comment]
hi,

this can be closed,

I managed to correct the correct settings.

thanks.

Majid
