### ISSUE TITLE
No description and cover for youtube channels

### ISSUE THREAD

**Issue by tXJtqlb3bbeKD1yW8SV7** [gpodder/gpodder#1502]
No description and cover for youtube channels:

![gpodder_48PrGLhenC](https://user-images.githubusercontent.com/88219689/233757225-61d889de-0377-403c-a87a-9c2869c84c00.png)

Windows 10
Gpodder 3.11.1
youtube-dlp 2023.02.17.

**Comment by auouymous** [comment]
Were these newly subscribed channels and has the issue been fixed with a recent update? Youtube sometimes has partial outages and the channel description and cover art can't be queried. Prior to 3.11.0, gpodder would erase the existing description and image, and restore them on the next successful update. It now catches the failure and does not overwrite them. However, if the problem happens while subscribing, there is no initial values until a later update.

**Comment by tXJtqlb3bbeKD1yW8SV7** [comment]
It is working now, thank you.
