### ISSUE TITLE
Posible idea: add the hour to published date?

### ISSUE THREAD

**Issue by Snippet24816** [gpodder/gpodder#1503]
And maybe sort by that criteria too?

**Comment by computerfreak105** [comment]
Thanks for this idea, would be great and useful. It would give us additional information about a file and show us if two files are the same. It still happens quite a lot that especially livestreams are downloaded twice or sometimes even three times.

 

Also, livestreams have the same name sometimes. So a time stamp would be ideal. Please use the time stamp from the server if possible, not from when the file is created on the end user’s computer.

 

 

Von: Snippet24816 ***@***.***> 
Gesendet: Montag, 24. April 2023 02:56
An: gpodder/gpodder ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [gpodder/gpodder] Posible idea: add the hour to published date? (Issue #1503)

 

And maybe sort by that criteria too?

**Comment by auouymous** [comment]
Sorting uses a unix timestamp, so episodes are already sorted by the second.

It would be nice to have more control over the format, such as changing the date layout and showing time above or below it. I use local patches that change the date format to '24apr2023' and right align the column so those varying width dates line up correctly, but also to move them away from the duration which looks like a time.

There are a couple issues showing the time. It could be added before the date as `12:34 Today` or `12:34 24apr2023` but that will be a problem for anyone using a narrow window such as mobile. Or it could be added on the line above the date using small text, which makes the date a little harder to read but isn't too bad.

![gpodder-time-date](https://user-images.githubusercontent.com/5005204/234178473-469130fe-082f-4136-943f-c9cf2313807f.png)

I'm not sure if this should have a setting in the view menu to toggle it on and off as needed, or if there should be a `Released+` column that always shows it.

**Comment by Snippet24816** [comment]
Mmm I'm not completely sure whats the best option, but perhaps it cant be more compact than using just numbers? like: D-M-Y
such as: 2023-04-25 16:11 and maybe combined with the idea of the hour on top. Also another idea that could save space may be to: 1. remove the year for current year 2. remove the month for current month and 3. remove the day for current day leaving only the hour in that case.

**Comment by computerfreak105** [comment]
2023-04-25 16:11 would be compact and good I think. I wouldn’t shorten it further like 23 instead of 2023.

 

Is this meant only to show in the Gpodder GUI or do I understand correctly that we’d have the possibility to get the date and time in the filename of downloaded episodes? So in the settings.json we could have a additional line like:

 

  "add_sorttime": true,

 

then we probably would need also the option like:

 

      "sorttime_after_sortdate"

 

 

 

 

 

 

Von: Snippet24816 ***@***.***> 
Gesendet: Mittwoch, 26. April 2023 05:35
An: gpodder/gpodder ***@***.***>
Cc: computerfreak105 ***@***.***>; Comment ***@***.***>
Betreff: Re: [gpodder/gpodder] Posible idea: add the hour to published date? (Issue #1503)

 

Mmm I'm not completely sure whats the best option, but perhaps it cant be more compact than using just numbers? like: D-M-Y
such as: 2023-04-25 16:11 and maybe combined with the idea of the hour on top. Also another idea that could save space may be to: 1. remove the year for current year 2. remove the month for current month and 3. remove the day for current day leaving only the hour in that case.

**Comment by Snippet24816** [comment]
> Is this meant only to show in the Gpodder GUI or do I understand correctly that we’d have the possibility to get the date and time in the filename of downloaded episodes? 

Not sure if that is covered by the extension RenameAfterDownload ? I don't know because I dont use it.

**Comment by Snippet24816** [comment]
@computerfreak105  
Sorry if I sounded harsh/ or I don't recap the exact word in english .. but it wasn't the intention..

**Comment by computerfreak105** [comment]
No problem here, I just was busy with work :-) Thanks for your idea. I checked it out right now. but as far I can tell adding the time stamp isn’t supported. Would be a nice addition.

 

https://gpodder.github.io/docs/extensions/renameafterdownload.html

 

All teh best, take care.

And English isn’t my native language either ;-)

 

 

 

Von: Snippet24816 ***@***.***> 
Gesendet: Freitag, 28. April 2023 22:09
An: gpodder/gpodder ***@***.***>
Cc: computerfreak105 ***@***.***>; Mention ***@***.***>
Betreff: Re: [gpodder/gpodder] Posible idea: add the hour to published date? (Issue #1503)

 

@computerfreak105 <https://github.com/computerfreak105> 
Sorry if I sounded harsh/ or I don't recap the exact word in english .. but it wasn't the intention..

**Comment by Snippet24816** [comment]
> No problem here, I just was busy with work :-) 

Ahh alright!!! 

>  I checked it out right now. but as far I can tell adding the time stamp isn’t supported. Would be a nice addition.

Agreed ;-)

> And English isn’t my native language either ;-)

Well it has downsides but perhaps also advantages? English may be easier to learn than my native lang and that means I can google in more languages which 'd be more unlikely to learn if english was my native..

> All teh best, take care.

you tooo :-)

**Comment by auouymous** [comment]
Added PR #1507 to show time in released column.

> "add_sorttime": true,

@computerfreak105 Do you have episodes with identical titles and different times on the same day? Any differences in the episode title would throw off sortdate (or sorttime) which is appended after the title. The `sorttime_after_sortdate` wouldn't be needed since the time MUST come after the date to properly sort it.

**Comment by computerfreak105** [comment]
<https://github.com/computerfreak105> @computerfreak105 Do you have episodes with identical titles and different times on the same day? Any differences in the episode title would throw off sortdate (or sorttime) which is appended after the title. The sorttime_after_sortdate wouldn't be needed since the time MUST come after the date to properly sort it.

 

It mostly happens with live streams. The funny thing is that I get two files with the same content, but the date stamp in the file name differs a day. I usually get par example livestreams dated from today and yesterday. but the creation dates and time shown in the windows explorer are identical.

 

And there is a mix in audio formats. Most streams are in .webm, but some are in .m4a. I maybe have 600 audio files from the last few weeks, and 64 of these are .m4a. Sometimes I’m getting the same stream in .webm and .m4a, but it doesn’t happen often, I’d have wait and look carefully for the next occurence.

 

Thanks.

 

 

 

 

 

 

Von: auouymous ***@***.***> 
Gesendet: Sonntag, 30. April 2023 06:36
An: gpodder/gpodder ***@***.***>
Cc: computerfreak105 ***@***.***>; Mention ***@***.***>
Betreff: Re: [gpodder/gpodder] Posible idea: add the hour to published date? (Issue #1503)

 

Added PR #1507 <https://github.com/gpodder/gpodder/pull/1507>  to show time in released column.

"add_sorttime": true,

@computerfreak105 <https://github.com/computerfreak105>  Do you have episodes with identical titles and different times on the same day? Any differences in the episode title would throw off sortdate (or sorttime) which is appended after the title. The sorttime_after_sortdate wouldn't be needed since the time MUST come after the date to properly sort it.
