### ISSUE TITLE
Error during synchronization

### ISSUE THREAD

**Issue by StephanieLabaule** [gpodder/gpodder#1514]
Hello everyone,

For some time, I have been randomly getting this error when syncing (‘Sync to Device’ from the ‘Extras’ menu) :

`&#x27;GioSyncTask&#x27; object has no attribute &#x27;custom_downloader&#x27;`

I reinstalled gPodder, but no improvement. 
If anyone has an idea, thanks.

**Comment by auouymous** [comment]
This was fixed by 3d690633eeed914e7a1bb2b44c35dc959f41df3e, but I have not had time to get a new release out yet.

If you are using Windows try installing an artifact from https://ci.appveyor.com/project/elelay/gpodder/builds/47122346/artifacts. For MacOS, try https://app.circleci.com/pipelines/github/gpodder/gpodder/586/workflows/9ce16b18-3f0b-422f-90d9-77fdf038eb80/jobs/952/artifacts. And for Linux you will need to run from git using https://gpodder.github.io/docs/run-from-git.html.

**Comment by StephanieLabaule** [comment]
Hello,

Thank you for your reply.
I do have a Windows version.
The Artifacts link is no longer valid.

Is there an upcoming gPodder update date?
Thanks !

**Comment by auouymous** [comment]
The current artifact for Windows is https://ci.appveyor.com/project/elelay/gpodder/build/artifacts, and https://app.circleci.com/pipelines/github/gpodder/gpodder/590/workflows/dfb22f6b-6bf3-49fa-a76e-bf7f63216be3/jobs/956/artifacts for Mac.

**Comment by StephanieLabaule** [comment]
Thank you so much !
Now wait and see.

**Comment by auouymous** [comment]
This is fixed in 3.11.2.
