### ISSUE TITLE
After upgrading to latest version Im getting error missing api-ms-win-core-path-l1-1-0.dll

### ISSUE THREAD

**Issue by Snippet24816** [gpodder/gpodder#1540]
On startup it says: 

> api-ms-win-core-path-l1-1-0.dll is missing from your computer

And is unable to intialize I'm Running W7..

![image](https://github.com/gpodder/gpodder/assets/108145509/0aaaf80f-342e-4d61-acd1-c98959a7395c)

**Comment by auouymous** [comment]
That is a Windows 10 library that was not backported to WIndows 7. Python 3.9 and later apparently do not support Windows 7. A bug report I saw was suppose to fix it so python showed an unsupported OS error instead of that missing DLL error.

Were you running 3.11.1 on Windows 7? 3.11.2 uses Python 3.11, and 3.11.1 used 3.10, so no recent release should have worked on Windows 7. You would need to install an old version of msys2 that used python 3.8 and then manually install gpodder's files in that environment.

**Comment by Snippet24816** [comment]
> Were you running 3.11.1 on Windows 7?

Yes :/

> You would need to install an old version of msys2 that used python 3.8 and then manually install gpodder's files in that environment.

May I ask more detail on how to do so?

**Comment by auouymous** [comment]
See https://github.com/gpodder/gpodder/blob/master/tools/win_installer/README.rst. The last version of msys2 to support Windows 7 is at https://github.com/msys2/msys2-installer/releases/tag/2022-10-28.

**Comment by Snippet24816** [comment]
Thanks, question: would that work in a portable gPodder installation? or it is the only way?

**Comment by auouymous** [comment]
I don't know what portable is, but if portable is able to do whatever it does, then this should theoretically also be able to do it.

**Comment by Snippet24816** [comment]
Ok frankly I don't know if I have all the knowledge to achieve this since never done something like that (which is recompiling gPodder files if I understood correctly), would it be too much to ask a command switch to use an older msys2 and the respective python dependency?

**Comment by auouymous** [comment]
You just need to install msys2 like any other program, and run a couple commands in the URL I gave you. It isn't easily possible for the project to run and support a second appveyor instance to generate Windows 7 builds using the older msys2, and it isn't possible for the current Windows build to contain the older msys2.

**Comment by Snippet24816** [comment]
Thanks for explaining, alright then installed, to be sure these are the commands?
>     Execute C:\msys64\mingw32.exe
>     Run pacman -S git to install git
>     Run git clone https://github.com/gpodder/gpodder.git
>     Run cd gpodder/tools/win_installer to end up where this README exists.
>     Execute ./bootstrap.sh to install all the needed dependencies.
>     Now go to the application source code cd ../..
>     To run gPodder execute ./bin/gpodder

**Comment by elelay** [comment]
@Snippet24816 you copy-pasted the full line, not just the command: run `pacman -S git`

**Comment by Snippet24816** [comment]
> @Snippet24816 you copy-pasted the full line, not just the command: run pacman -S git

Ahh I see my bad, thank you so much!!

**Comment by Snippet24816** [comment]
![image](https://github.com/gpodder/gpodder/assets/108145509/5eacc6ba-5d9a-4d08-9369-ccb273de9b9e)

**Comment by Snippet24816** [comment]
![image](https://github.com/gpodder/gpodder/assets/108145509/6a0d8807-43f6-4fb3-908d-e582ef38ec8c)

**Comment by auouymous** [comment]
I don't understand why several of those packages are older versions than what current build and the last working build for Windows 7 use. The two packages you have issues with are `perl-IO-HTML-1.004-2` and `perl-HTTP-Cookies-6.10-2`, and several others have re-releases as well.

**Comment by Snippet24816** [comment]
Question: can git be downloaded manually and installed not through pacman?

**Comment by Snippet24816** [comment]
I solved it!!! ^^ https://github.com/msys2/MSYS2-packages/issues/2397#issuecomment-868954414
here was the trick now I have installed git with pacman

**Comment by auouymous** [comment]
I don't know if deleting that directory is the correct way, but the appveyor build runs `pacman -Syuu --noconfirm` twice before building. @elelay Should that command be used before installing git?

**Comment by Snippet24816** [comment]
![image](https://github.com/gpodder/gpodder/assets/108145509/0fdaff93-56c1-45bf-9131-c273c0cd23db)
Here i am : Execute ./bootstrap.sh to install all the needed dependencies.

**Comment by auouymous** [comment]
Very important, that program is used to install all of gpodder's dependencies.

**Comment by Snippet24816** [comment]
I see thats why I was getting: /usr/bin/env: ‘python3’: No such file or directory

**Comment by Snippet24816** [comment]
What should I do?

**Comment by tordenflesk** [comment]
Update Python? https://github.com/adang1345/PythonWin7
No need to mess around with with git or msys.

**Comment by auouymous** [comment]
@tordenflesk How do you update the python inside gpodder's Windows build?

**Comment by tordenflesk** [comment]
I haven't. Runs just fine:
https://i.imgur.com/Kt7SmZF.png

**Comment by auouymous** [comment]
@tordenflesk So you simply installed PythonWin7 and gpodder 3.11.3 just works on Windows 7?

**Comment by Snippet24816** [comment]
@tordenflesk Great !! will try and report back, thank you so much :-)
update: "For Python 3.11 or higher, remove the usage of features that are not available on Windows 7." wich are those unavailable features?

**Comment by Snippet24816** [comment]
I'm afraid it didn't work here :(

**Comment by tordenflesk** [comment]
> I'm afraid it didn't work here with portable version .. :( installed python-3.11.5-amd64-full.exe

Did python get added to your PATH?

You can check using: echo %PATH:;=&echo.% in cmd

If you see lines like C:\Python311 and C:\Python311\Scripts you might just need to log out and back in, or a reboot.

**Comment by Snippet24816** [comment]
Did python get added to your PATH?
I did the default installation, modifying it..

> If you see lines like C:\Python311 and C:\Python311\Scripts you might just need to log out and back in, or a reboot.

Alright, yea I'm seeing those..

**Comment by Snippet24816** [comment]
Apologize for the late response.. restarted computer and now I'm seeing the following error
![image](https://github.com/gpodder/gpodder/assets/108145509/7901ac14-9237-44d5-b9ff-081c12e2f49b)

**Comment by Snippet24816** [comment]
Ok, I should had said this before, I really hate rebooting cause it takes like 8minutes or more, but is not because of lack of interest, but once I do I will post here, thanks

**Comment by Snippet24816** [comment]
Okey same error as always I'm afraid

**Comment by Snippet24816** [comment]
In case someone happens to have the same problem, this was the solution : https://github.com/nalexandru/api-ms-win-core-path-HACK/releases

**Comment by auouymous** [comment]
@Snippet24816 So you have gpodder 3.11.4 working on Windows 7 with that library? If you feel experimental, https://ci.appveyor.com/project/elelay/gpodder/builds/50144680/artifacts "_might_" be the first working Windows build since 3.11.4 was released.

**Comment by computerfreak105** [comment]
Thanks for trying. It doesn’t work yet. The windows gpodder doesn’t start yet.

 

And when I’m trying to run CLI GPO under Windows 11 I get this:

 

----------------------------------------

C:\gpodder-3.11.4-portable 1.0.1231\data\bin>gpo.exe

Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "C:\gpodder-3.11.4-portable 1.0.1231\data\lib\python3.11\site-packages\gpodder_launch\gpo.py", line 135, in <module>

    import gpodder  # isort:skip

    ^^^^^^^^^^^^^^

  File "C:\gpodder-3.11.4-portable 1.0.1231\data\lib\python3.11\site-packages\gpodder\__init__.py", line 41, in <module>

    from gpodder.build_info import BUILD_TYPE

ModuleNotFoundError: No module named 'gpodder.build_info'

 

----------------------------------------

 

 

The last working Windows version i have is gpodder-3.11.4-portable 1.0.1205. But I had to copy the share/gpodder directory from the git repo

to the data/share/ in the portable install dir. In order to make it work. In the 1231 version this doesn’t work as far I can tell.

 

 

Von: auouymous ***@***.***> 
Gesendet: Donnerstag, 11. Juli 2024 03:21
An: gpodder/gpodder ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: Re: [gpodder/gpodder] After upgrading to latest version Im getting error missing api-ms-win-core-path-l1-1-0.dll (Issue #1540)

 

@Snippet24816 <https://github.com/Snippet24816>  So you have gpodder 3.11.4 working on Windows 7 with that library? If you feel experimental, https://ci.appveyor.com/project/elelay/gpodder/builds/50144680/artifacts "might" be the first working Windows build since 3.11.4 was released.

**Comment by auouymous** [comment]
Darn. I was hoping it would work because the content files finally mostly match, excluding the pyc/pycache files/directories which shouldn't matter. At least we are closer and maybe @elelay can figure it out in a couple weeks.

**Comment by tomasts248** [comment]
> So you have gpodder 3.11.4 working on Windows 7 with that library?

Yes

> Thanks for trying. It doesn’t work yet. The windows gpodder doesn’t start yet.

In order to work youy have to do copy the .dll like this: The 32-bit version goes into SysWOW64 and the 64-bit version goes into System32.

> "might" be the first working Windows build since 3.11.4 

That is using this? https://github.com/nalexandru/api-ms-win-core-path-HACK/releases

**Comment by Snippet24816** [comment]
> So you have gpodder 3.11.4 working on Windows 7 with that library?

Yes

> Thanks for trying. It doesn’t work yet. The windows gpodder doesn’t start yet.

In order to work youy have to do copy the .dll like this: The 32-bit version goes into SysWOW64 and the 64-bit version goes into System32.

> "might" be the first working Windows build since 3.11.4 

That is using this? https://github.com/nalexandru/api-ms-win-core-path-HACK/releases

**Comment by computerfreak105** [comment]
Hi Snippet24816

 

Thanks for explaining this to me. I did copy these files as you wrote but it’s not working yet for me under Windows 11. Would have been nice, but I guess I’ll have to wait for some time and hope the .1205 release works until then.

 

Take care.

 

 

Von: Snippet24816 ***@***.***> 
Gesendet: Donnerstag, 11. Juli 2024 16:29
An: gpodder/gpodder ***@***.***>
Cc: computerfreak105 ***@***.***>; Comment ***@***.***>
Betreff: Re: [gpodder/gpodder] After upgrading to latest version Im getting error missing api-ms-win-core-path-l1-1-0.dll (Issue #1540)

 

So you have gpodder 3.11.4 working on Windows 7 with that library?

Yes

Thanks for trying. It doesn’t work yet. The windows gpodder doesn’t start yet.

In order to work you have to do copy the .dll like this: The 32-bit version goes into SysWOW64 and the 64-bit version goes into System32.

"might" be the first working Windows build since 3.11.4

That is using this? https://github.com/nalexandru/api-ms-win-core-path-HACK/releases
