### ISSUE TITLE
Code page invalid

### ISSUE THREAD

**Issue by Slootpp** [gpodder/gpodder#1548]
Many of the entries in the menu bar are replaced by an error message [Invalid UTF-8] ?
Will it be fixed by a new version, or is there a personnalisation way to fix the problem ?
![Capture d'écran 2023-08-25 124849](https://github.com/gpodder/gpodder/assets/30004332/7afbd793-8878-4cca-adf3-aa5b7d8a4ab1)
Thanks for all

**Comment by auouymous** [comment]
Are you using Windows? If so, this has been fixed (see #1538) and will be in a new release soon. In the mean time, you can install https://ci.appveyor.com/project/elelay/gpodder/builds/47866410/artifacts to fix the problem.

**Comment by alexis26** [comment]
Hi,

I just update from 3.11.1 to 3.11.2 (windows portable version)

I haven't this problem and it appeared with the ugrade...

**Comment by kernal64** [comment]
> Are you using Windows? If so, this has been fixed (see #1538) and will be in a new release soon. In the mean time, you can install https://ci.appveyor.com/project/elelay/gpodder/builds/47866410/artifacts to fix the problem.

The above link is no longer working, because the artifacts are older than a month but there is still no fixed version released. I recently started to listen to some regular podcasts. On my smartphone I use AntennaPod and sync my settings with nextcloud-gpodder. Now I tought, I can use gpodder on my Windows- and Linux-Machines with nextcloud-gpodder as well. So I started today but stumbled upon this error.

Can you please release a fixed version or for the meantime republish above artifacts?

thanks in advance
k.

**Comment by auouymous** [comment]
https://ci.appveyor.com/project/elelay/gpodder/builds/48147684/artifacts is the latest artifact and will be released in a few days.

**Comment by kernal64** [comment]
I already figured out that I can switch to english by setting the environment variable "LANGUAGE=english". For my purposes it was sufficient. Ironically, _gpodder_ doesn't sync with [nextcloud-gpodder](https://github.com/thrillfall/nextcloud-gpodder#nextcloud-gpodder). I know use [Podcast Merlin](https://github.com/yoyoooooooooo/Podcast-Merlin--Nextcloud-Gpodder-Client-For-Windows) on Windows and for Linux I'll take a look on both podcast-clients support by _nextcloud-gpodder_.

Many thanks anyway!

**Comment by auouymous** [comment]
3.11.3 is now available.
