### ISSUE TITLE
Using youtube-dl, "Check for new podcasts" ALWAYS hangs up on #141, regardless of which feed it is.

### ISSUE THREAD

**Issue by kb6ojs** [gpodder/gpodder#1562]
I recently started using the youtube-dl extension.  Now that I have it working properly, every time I run the "Check for new episodes" via the button at the bottom of the podcast list, it always hangs up when checking feed #141, regardless of which feed that happens to be.  I originally thought it was a problem with the feed that it happened to be checking, so I removed it, but it failed yet again on #141, even though that was a different feed.  I have almost 500 feeds in my list, which I know is an incredibly large list, but I don't download and watch or listen to every one (my lifespan is obviously too short 😉) but I pick and choose which episodes I want to play.  Any suggestions?

**Comment by kb6ojs** [comment]
Failed to mention, I am using 3.11.2 on Windows 11.  Sorry.

**Comment by auouymous** [comment]
You can access logs from the gPodder menu, do they contain any relevant errors after performing a failed update?

**Comment by kb6ojs** [comment]
Thanks for the reply.  There's a LOT of stuff in there, mostly from single-feed updates, so i will will delete the log and do another attempt so I have a fresh log to look at.  Will also test it against the just-released 3.11.3 version on the chance that it's fixed in that version somehow.

**Comment by kb6ojs** [comment]
[2023-10-01.log](https://github.com/gpodder/gpodder/files/12778327/2023-10-01.log)

Attaching log file generated by 3.11.2 this morning.  It made it to feed #146 this time, amazingly enough, before not quite hanging up (I was able to cancel the update process with the big "X" button).  I **suspect** the problem is due to a YouTube feed just taking forever to update, since I recently and successfully re-enabled the youtube-dl extension, which apparently wants to go back to the "Genesis" of the YouTube feeds and retrieve every single video posted to each YouTube channel...!

As to the contents of the log, I really don't know what each of those warning entries mean exactly (forgive my ignorance, please), so I will leave it to the dev team to use their Jonny Quest secret decoder rings to figure it out... 😉

//Steve//

**Comment by auouymous** [comment]
Ya, using the `manage channels` setting in the extension will cause it to take a while, even more so if your episode limit is high. For me, yt-dlp (outside of gpodder) takes 5 seconds plus 1 second per episode to read a channel, so a 100 episode channel would take 105 seconds and more than 101 requests to youtube. I know why it needs the >101 requests but I'm not sure why it takes so long because I recently wrote my own code that can fetch and process each request 10 faster than yt-dlp does.

There were no issues in the log, other than possible mild database corruption or leakage because you have orphaned episodes.

Can you get produce another log using https://gpodder.github.io/docs/windows.html#debugging-gpodder-on-windows and let it hang?

**Comment by kb6ojs** [comment]
This can be closed.  It turns out that with youtube-dl enabled, gPodder is going through **every** YouTube feed and pulling down **all** of the items in that feed.  I'm presuming that it will be faster once this process is complete, but right now the updating process is in its **third day** of operating to get caught up with everything!
