### ISSUE TITLE
Limit of 200 episodes? 

### ISSUE THREAD

**Issue by GeneralMidi** [gpodder/gpodder#1597]
Hi, just downloaded the portable version for Windows. Added a podcast subscription that I know has more than 500 episodes, and I can only see the last 200.

I'm wondering if there is a limit hardcoded for 200 episodes, and if so, could this please be removed.

**Comment by GeneralMidi** [comment]
Ok, I saw this in the settings and closed the issue. However, the limit is 1000 episodes. The podcast I want to save files for has 830 episodes and when this crosses the 1000 limit, I'll have problems. Please consider upping the limit.

**Comment by auouymous** [comment]
The GUI enforces the limit of 1000. However, you can click the edit config button, search for 'limit' and change its value to anything you want. Keep in mind that problems may arise, especially if using a slow device, because gpodder sends every episode to gtk, even if you can't see them.

**Comment by mhussaincov94** [comment]
say and if you want to skip the gui completely, open settings.json which is found in your gpodder directory where the databace and podcasts are downloaded.
change the folowing setting
episodes": 
the space after the : is intentional.
add a stupidly big number and you'll have no worries.
just frequently sync your podcasts to a seperate hdd or device like i do which will keep the ui speedy.
I make it so that after a epesode is synced it is deleted from gpodder.
I have disabled the view all epesodes ability if that is active, it makes the ui freeze.
I hope this helps you.
