### ISSUE TITLE
Is there a way or preference to increase the use of Processor? in order to reduce episodes load times.

### ISSUE THREAD

**Issue by Snippet24816** [gpodder/gpodder#1604]
My computer is using maximum of 25% would it be possible that it used more cpu like 50% in order to load faster the episodes and reduce startup times?

Regards

**Comment by auouymous** [comment]
Do you have a 4 core processor? Gpodder only uses multiple threads when downloading, so during startup only one thread would be active, and a 4 core processor would show a maximum of 25% usage. There are two bottlenecks during startup: loading from disk and loading episodes into gtk's treeview. Getting a fast SSD or reducing your database size by storing fewer episodes is the only way to make it load faster. And since gtk is single threaded, reducing the number of episodes is the only way for gpodder to fill the treeview faster.

I profiled the episode treeview code a while back and 62% of the time was spent inside gtk when you only have deleted or downloaded episodes. The other paths are really slow, so I suggest not keeping around a lot of episodes that aren't either deleted or downloaded. Moving the 38% of non-gtk code to a second wouldn't make it that much faster because it must send the data back to the first thread to send it to gtk. The non-gtk code is also on a timer, so the main thread is idle briefly every 500ms to keep the UI responsive. That would be much harder to guarantee if one or more other threads were constantly sending data to the main thread. Two threads would completely saturate the main thread, except in the non-deleted/downloaded paths where you could see three threads feeding the gtk thread and using 100% cpu on a 4 core processor. If someone wanted to try implementing a responsive worker pool, you might only see 25% faster loads. But it would need to detect single core systems and not use a second thread because that would kill performance on those already slow systems.

Another way to improve startup speed is to disable the `"All episodes" in podcast list` in View menu. You lose that feature, but gpodder wouldn't need to load every episode, only those in the first channel.

**Comment by Snippet24816** [comment]
> Do you have a 4 core processor? 
2 Cores 2 and 4 Threads

Thanks for explaining, good to know this. 
Question: for the second bottleneck instead of reloading the whole channel could only the new episodes be added without having to load again all the older ones?

**Comment by Snippet24816** [comment]
I see, thanks for explaining :+1:
