### ISSUE TITLE
gtk3: Should menu items of the menu bar have icons?

### ISSUE THREAD

**Issue by adamvoss** [gpodder/gpodder#161]
In gtk2, most menu entries had a pictorial glyph associated with the text to indicating the action.

In gtk3, these images are currently absent.  This implementation decision was intentional because images are "out of fashion."

Are users okay not having images in under the menu bar?

From #150

**Comment by vossad01** [comment]
I personally have not missed the images in the menu bar and think the menus look pretty clean as is (gtk3). I did not notice the change at first when going to Gtk3 and would be fine it they remained absent.

I do appreciate those that are present in the context-menu.

**Comment by thp** [comment]
IMHO we should drop the icons in the application-level menus.

As for the context menu icons, we can keep them but maybe reduce the amount of icons we have (only have icons for items where it makes sense).

**Comment by vossad01** [comment]
For ease of reference, here are the main context menus:

**Podcasts:**
![screenshot from 2016-11-08 16-03-55](https://cloud.githubusercontent.com/assets/965439/20119390/f715bfc8-a5cd-11e6-811f-201272421b25.png)

**Episodes:**
![screenshot from 2016-11-08 16-03-37](https://cloud.githubusercontent.com/assets/965439/20119388/f65416d4-a5cd-11e6-8389-746c5563ed70.png)

**Download Queue Episodes:**
![screenshot from 2016-11-08 16-07-40](https://cloud.githubusercontent.com/assets/965439/20119392/f7387130-a5cd-11e6-9872-28dd9d9b8dc5.png)

**Comment by elelay** [comment]
Icons have not been requested since release...

**Comment by Imerion** [comment]
I really hope this will be kept at least as an option. I remember activating a plugin for Firefox that added icons to menus, and suddenly the whole program was much easier to use and I could really feel how much quicker I found the option I wanted.

I think these icons are very important for many reasons. Colorful icons makes it much easier to remember where to look and quickly find the option you want since have more things to go by. I work with helping people with various neurological impairments such as aphasia, and for most of them this would mean the whole difference of being able to use the app or not, even after loads of training. Having small things like that to "connect" your memory with is so very important, and only text or single, grey glyphs is not enough.
