### ISSUE TITLE
Hanging on opening when loading incomplete downloads

### ISSUE THREAD

**Issue by Prospero1960** [gpodder/gpodder#1617]
Hi -

gpodder 3.11.4 on Windows is hanging on opening with message:

"some episodes have not finished downloading in a previous session" and "Cleaning up".

See attached image.

![gpodder 2024-03-28](https://github.com/gpodder/gpodder/assets/83580649/e48e233b-a651-4073-a6da-f9bc7facbff2)

**Comment by auouymous** [comment]
Try this https://github.com/gpodder/gpodder/issues/1499#issuecomment-1492554549.

**Comment by Prospero1960** [comment]
That fixed it - thanks a lot. There was just one zero-sized .partial file, which I deleted. Maybe worth fixing the code to deal with this.

**Comment by computerfreak105** [comment]
If we remove the partial 0 kb files will gpodder download them again or will we miss out on the files we remove? Or asked differently, does removing the 0 kb files affect the database?

**Comment by auouymous** [comment]
> Maybe worth fixing the code to deal with this.

We can only fix reproducible problems or problems that write backtraces to the log file. It can't get fixed until it happens to me or someone else who can debug the cause.

> If we remove the partial 0 kb files will gpodder download them again or will we miss out on the files we remove? Or asked differently, does removing the 0 kb files affect the database?

A partial file is created when you tell gpodder to download an episode. That file remains at zero bytes until gpodder actually begins downloading it, and then it becomes non-zero as data is downloaded to it. Gpodder renames the file once the download is complete, stripping its 'partial' extension.

If you restart gpodder while downloads are active, it sees these partial files (either zero or non-zero) and resumes downloading them. The issue is that something is causing gpodder to lockup after finding these files. Removing the files just means you have to manually tell gpodder to download them again, and removing non-zero files just means you lose the partial data previously downloaded.

There is no harm in removing the partial files, unless wasting more bandwidth costs you more money. In that case, remove all of the zero files first and test if gpodder starts up. If not, remove each non-zero partial file, one by one, starting with the smallest.
