### ISSUE TITLE
[bug] missing episodes / gpodder does not show all episodes

### ISSUE THREAD

**Issue by ulu** [gpodder/gpodder#1626]
Some weeks ago I added
```
https://www1.wdr.de/mediathek/audio/wdr3/meisterstuecke/meisterstuecke-podcast-100.podcast
```
to AntennaPod.

Today I tried the same in ```gPodder 3.11.4 (2023-10-11)``` on a ```Windows 10``` machine.

I got irritated that older episodes are not shown in gPodder. So I checked the file from the URL. The older episodes are in the file but gPodder does neither show them nor find them by gPodder-search/filter function. For example "Peter Tschaikowsky: Romeo und Julia":

Podcast-File: corresponding item element found at line 6890
gPodder with Filter "Tschaikowsky" or "Romeo": no entry regarding the searched episode

Podcast-File publication date: ```<pubDate>Fri, 20 Apr 2018 09:55:09 GMT</pubDate>```
earliest Publication file in gPodder: ```14.05.2020```

Even a visibility element in the file does not explain why it is not shown in gPodder:
```
<ard:visibility>
        <ard:visibleFrom>2022-08-18T20:10:25</ard:visibleFrom>
        <ard:visibleUntil>2099-12-30T00:00:00</ard:visibleUntil>
</ard:visibility>
```

Poddr (https://github.com/Sn8z/Poddr/) works as expected and shows old episodes like AntennaPod does.

**Comment by elelay** [comment]
Hi ulu,
changing max episodes to 300 in gPodder > Preferences > **Updates** and refreshing will get you the older episode you are looking for.

**Comment by ulu** [comment]
Hi elelay, thank you! Using your hint fixed my issue.

I don't understand why I have a fixed value of 200 episodes which was the number for max episodes per podcast at my fresh installation. This makes no sense to me. If I add a new Podcast I want all episodes and not the latest 200.

Unfortunately the highest number for "for max episodes per podcast" in UI is 1000. If I edit the config file  I can use e.g. 1e16. After that the UI shows me the large number but I can only decrease it. All togehter IMHO a confusing behavior.

Should I change the topic to [enhancement] or [feature request] for "default to MAX_INT episodes per podcast"? Or should I open a new issue with reference to this issue?

**Comment by elelay** [comment]
You're not alone in this request, but equally people won't want to have a sluggish experience.
See #1597
Maybe a FAQ should be added?

**Comment by ulu** [comment]
I see updating the FAQ as a quick workaround, but one that only reaches the user when they find out about the problem. In the long term, it would be better to solve the problem (see below for ideas).

What I do not understand the point of "sluggish XP". I do not have any idea about the software architecture of gPodder. But we talk about an UI which should run in a separate thread (hopefully it already runs separated). So I would like to see following improvements of the UI:

1. add a counter for existing episodes vs. downloadable episodes, e.g. 2.000/10.000 directly after / below the name of the podfast. New Episodes can also be part of these numbers like: "current available / total available / new"
3. add a progress bar / circle to show the update process of every podcast while its updated. In this case the user can already use gPodder while it updates all episode lists.

This provides the user with all the necessary information and the user interface becomes neither confusing, cluttering nor sluggish.

Should I open a separate ticket for this change request?

**Comment by auouymous** [comment]
Disclaimer: Not feeling well, hopefully this makes sense and answers your questions, it didn't the first few times I wrote it.

> What I do not understand the point of "sluggish XP"

Gtk is single threaded, and gpodder can only load episodes into it with one thread. This causes it take a very long time to display the episode list when users on slow machines have a hundred podcasts each with thousands of episodes.

Downloading episodes also updates the entire episode list every second. The refresh period had to be dynamically adjusted because of the long refresh time, which locked up the UI while downloading for users with a high episode limit. The UI is now "usable" for these users but every 5 seconds or so it freezes for a couple seconds.

Updating feeds also takes a lot longer with a higher episode limit, leading to a slow experience.


> add a counter

Gpodder must read the entire feed file to make that happen, which leads to very long update times. Some feeds are also paginated which means numerous network requests per feed. And feeds can remove episodes, which means gpodder must read the entire feed every update. A counter would impact every user, and would need a setting that defaults to off, making it useless.

Then there is the youtube-dl extension which takes one second and one network request for every single episode.

> add a progress bar

The progress bar for new feeds does need some work as it is usless right now. The feed does not contain a count of episodes in it, but gpodder could assume it contains `episode.limit` and increment progress bar. A feed with 10 episodes would increment to 5% and then finish. The progress bar could be removed if all episodes needed to be counted, as gpodder would have no idea what the upper limit was.

The same goes for the "update all feeds" progress bar which currently increments for the total number of feeds you have. We could add a secondary progress bar to indicate progress in the current feed, using episode limit as an upper bound. But if gpodder must scan the feed to completion to update a total episode count, it makes the secondary bar useless as well.

**Comment by ulu** [comment]
I hope you are well again!

Thank you for your detailed explanation. I am surprised about Gtk shortcomings. Maybe this explains some UI issues of GIMP.

In the end, we have to accept Gtk with its limitations or switch to another podcast software. :-/
