### ISSUE TITLE
Could podcasts with no changes be cached?

### ISSUE THREAD

**Issue by Snippet24816** [gpodder/gpodder#1628]
If I click on video tab, then I switch to Audio, then going back to Video without any change in terms of new downloaded episodes it loads them as they were loaded for the first time which is very slow, could a a sort of cache be used for podcasts without changes?

**Comment by auouymous** [comment]
The podcast is cached on your disk in the gpodder database. The part that is slow is when gpodder sends the episodes to gtk. It would need to create a separate model for each podcast, and the all podcasts, and then switch the model on the episode pane when switching podcasts. It would only load the model when the podcast was accessed, but each time you switched it would consume more memory. This wouldn't be optional, all users would need to use this because supporting single and multiple models would be complex.

Currently, when a download reports progress, it causes the episode list to update. This would need to be changed to only update the model for the podcast and the all-podcasts model. It would he complicated to do that and everything else that assumes a single model.

Are you using an old version for Win7, or did you get a newer version working?

**Comment by Snippet24816** [comment]
Mmm I understand the points and concurr.

> Are you using an old version for Win7, or did you get a newer version working?

I'm afraid the old vesion on w7 thanks for asking. I dont like the fact that the computer is fast enough en general, but W11 doesn't support the motherboard maybe just to make you upgrade :/

**Comment by auouymous** [comment]
Can you upgrade to win10, it has 1.5 years of support remaining and might get more because 70% of users are still on it. Or you could try linux. ;)

**Comment by Snippet24816** [comment]
I made it thanks to this https://github.com/nalexandru/api-ms-win-core-path-HACK/releases
