### ISSUE TITLE
Filter age not working with < operator?

### ISSUE THREAD

**Issue by Snippet24816** [gpodder/gpodder#1651]
I'm trying to optimize gPodder loading times and tried to use the filter (age < 3) to get episodes for last 48 hours, but is loading older episodes as well. Tried as well with the == operator, is there any current workaround?

**Comment by auouymous** [comment]
`age` only works for downloaded episodes, anything not downloaded returns a `0`, which is less than 3. Using `(downloaded and age < 3)` will do what you want.

I'm not sure why the file's age is being used here, I would expect the episode's release date to be what users expect. Some users might however expect age to be the downloaded date. I need to look into the best way to handle this and will then create a PR.

**Comment by Snippet24816** [comment]
Thanks for explaining, 

> I'm not sure why the file's age is being used here, I would expect the episode's release date to be what users expect. Some users might however expect age to be the downloaded date. I need to look into the best way to handle this and will then create a PR.

Perhaps add "published" in addition to "age"?

**Comment by auouymous** [comment]
Ah, thank you for that naming suggestion. I did a search to see if it was already added and found `since`, which returns the days since episode was published.

**Comment by Snippet24816** [comment]
Thanks to you!! :)
May I ask if possible how did you find it? so that I can improve my search skills :D
Also it works just fine, a detail it seems to calculate based on the hour, for example for (since < 3) it generates a few results too from 3 days ago but very few ones so I suppose it works like that...

**Comment by auouymous** [comment]
I looked in "src/gpodder/query.py" (https://github.com/gpodder/gpodder/blob/master/src/gpodder/query.py).

I just tested and `(...).days` is always rounded down, so 2 days and 23 hours ago is just 2. It might be better if it uses `(...).seconds / 86400`, so it returns 2.96 in case users expect finer granularity such as `since < .5`. The only case I can think of it breaking is `since == 3` which currently matches episodes 3-4 days old, and would now only match episodes that are exactly to the second 3 days old when the query is run.

**Comment by Snippet24816** [comment]
> I looked in "src/gpodder/query.py" (https://github.com/gpodder/gpodder/blob/master/src/gpodder/query.py).

Thanks!!! I looked there too but now I realize I didn't read all, so thats the lesson :)

> I just tested and (...).days is always rounded down, so 2 days and 23 hours ago is just 2.

Thanks that was it :+1:
