### ISSUE TITLE
Migrate bugs.gpodder.org to Github

### ISSUE THREAD

**Issue by adamvoss** [gpodder/gpodder#186]
Would it be possible to redirect https://bugs.gpodder.org to https://github.com/gpodder/gpodder/issues?

I don't know how long the banner has been on that issue tracker telling people to come here instead.  However, a quick look shows there are issues and reports there made within the last 3 months, and I don't know that anyone is really checking there.

**Comment by thp** [comment]
We'll have to coordinate this with @paulgit (who hosts bugs.gpodder.org), it would be nice to still keep an archive of the old bug reports for reference, but most likely we can just redirect it. Let me think about this a bit :)

**Comment by paulgit** [comment]
@thp we could redirect bugs.gpodder.org but perhaps have something like oldbugs.gpodder.org for the old bug tracker.

@vossad01 FYI the banner has only been there for about 6 weeks.

**Comment by vossad01** [comment]
@thp The title might suggest trying to move the individual issues into GitHub.  Was that a consideration or just a misinterpretation on my part?

Given that there have been no new issues created for gPodder since the banner, I think the banner has been effective, and I would be fine closing this with no action. There are various links that could still be updated, but the banner seems to be sufficient.
