### ISSUE TITLE
A Few Small Suggestions

### ISSUE THREAD

**Issue by PamboHambo** [gpodder/gpodder#192]
I just started using gPodder and really like it, but I feel it's missing a few basic features/options (and if these options already exist, I'd suggest making them easier to find or at least include them in the help page):

1. Tray icon with options to close-to-tray and minimise-to-tray (and start-minimised-to-tray). I like to leave the program running throughout the day, kinda irritating to have it on the task bar the entire time. I'm currently using RBTray to force gPodder to the system tray, but a native tray option would be better.

2. Option to start with the OS at boot.

3. Make it easier to define a download location. The only way I found to do it was to "mount" a file system folder as a device, but even after all of that tinkering it didn't work for me when I ran the sync tool. Seems needlessly convoluted, regardless.

4. Audio notifications or perhaps a tray balloon notification for new episodes.

That's all, just a few small things, otherwise the program is perfect!

Thanks for reading!

**Comment by vossad01** [comment]
@PamboHambo  Thank you for your suggestions.

 1. Based on the terminology you used, I am guessing you are running Windows.  I don't know if it works on Windows, but there does exist an icon for some desktop environments.  Under "Preferences > Extensions" try "Gtk Status Icon", and if on Ubuntu there is also the "Ubuntu App Indicator."  This is being considered for removal in a future version though #160.

 2. Again assuming you are on Windows, are you familiar with the "Startup" folder.  If you put a shortcut to gPodder (or any other application) there, it will launch on startup.

 3. I would agree that it would be an improvement if this could somehow be set under "Preferences"; however, there are [instructions on how to accomplish this in the User Manual](http://wiki.gpodder.org/wiki/User_Manual#Changing_the_downloads_folder_location_and_the_gPodder_Home_folder).  [The FAQ](http://wiki.gpodder.org/wiki/FAQs) also directs to the User Manual for how to do this.  I have used these steps successfully on both Windows and Linux.  On Windows you even get a bit of a GUI to do it.

 4.  I honestly don't know if released versions have these. They do exist in the most recent development version, but no idea when that might have a beta available..

When you create issues on GitHub, please consider creating one issue per bug or request.  That makes it easier for projects to manage and people to follow because all discussion pertaining to pertaining to a single issue are together and issues can be closed once they are resolved. :smile:

**Comment by PamboHambo** [comment]
Ahh sorry, I'll be sure to do that in future ;)

Cheers mate.

**Comment by thp** [comment]
I guess we can close this -- @PamboHambo please open separate issues / feature requests for the points that haven't been solved for you by @vossad01's answers.
