### ISSUE TITLE
Please add a search/filter function for podcast titles (and maybe description)

### ISSUE THREAD

**Issue by godot42** [gpodder/gpodder#207]
I would like to be able to search/filter the displayed (downloaded) podcasts.
Often I know some words from the title, but not the full title, so I would like to be able to search for it.
(I tried to find the functionality - because it seems somewhat obvious - but failed in the application itself, the manual and the wiki.

**Comment by thp** [comment]
It's kind of hidden:

1. Make sure the keyboard focus is on the episode list
2. Start typing what you want to search
3. The search field will appear and the list will be filtered

You can either type text, and it will be filtered for this or you can type "(" and then an expression and then ")", e.g. `(downloaded and not played)` to filter for specific things, e.g. `(downloaded and 'winter' in title)`. The list of adjectives and nouns available is here: https://github.com/gpodder/gpodder/blob/master/src/gpodder/query.py#L47 -- the syntax of the expressions inside `()` is the same as for Python expressions. Some other examples: `(downloaded and minutes < 30)` (all downloaded episodes that are shorter than 30 minutes long), `(downloaded and audio and since > 30)` (all downloaded audio files that have been released more than 30 days ago), ...

**Comment by thp** [comment]
Closing this as done :)

**Comment by domOrielton** [comment]
Could this be added as an enhancement - to add it  menu item to activate the search field? It works brilliantly when you know it is there but finding it is tough. I couldn't find it in the wiki and most users might not look in the github issues list which is where I found it in the end :)
