### ISSUE TITLE
Please document youtube subscription features

### ISSUE THREAD

**Issue by Vrihub** [gpodder/gpodder#213]
I can't find any information in the wiki about the "Extras" -> "Update Youtube subscriptions" menu command, and, more generally, about the use API keys for youtube.

**Comment by thp** [comment]
It's here: http://wiki.gpodder.org/wiki/Youtube

**Comment by Vrihub** [comment]
Ah, thanks. I tried to create an account on the wiki, to link that page from the User_Manual page, but when I click on the "Create your account" button, I only get a blank page, and no email notification (and if I try to login with the credentials, I get a "user not found" error message).

**Comment by vossad01** [comment]
@Vrihub I think you can access the information on the wiki without having an account.  Were you successful at getting the information?

If you have a new issue with creating accounts on the wiki, a new issue would help track that issue.  Since this issue is marked as closed, it is not as likely to get attention.

**Comment by Vrihub** [comment]
> I think you can access the information on the wiki without having an account

Of course, but I was trying to add a link to the youtube page in the main User_Manual page, so that people can find that information more easily.
