### ISSUE TITLE
alert handshake failure

### ISSUE THREAD

**Issue by dbBerkeley** [gpodder/gpodder#234]
I am trying to access the NY Times Daily podcast at http://feeds.podtrac.com/zKq6WZZLTlbM with current gpodder and Windows 10. But I get an error (I hope I type this correctly - I could not find a way to copy the error message to the clipboard):
I/O Errpr [Errno 1] _ssl.c:503: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure: None - The Daily
![image](https://cloud.githubusercontent.com/assets/24510958/23142202/8e7f7c80-f76f-11e6-8916-330ed2579bd0.png)

**Comment by vossad01** [comment]
If this consistently fails, it is possible the SSL library gPodder is using does not support the minimums supported by the server.  It is also possible there was an issue on the NY Times' side or somewhere on the network.  I added the podcast and successfully started the download for that episode using the current git master (ab48ea24f29a3d237396848520d27b3dba23635d) on Linux Mint.

If you can reproduce this, could you try launching gPodder from a cmd prompt?  When the error occurs, more more detailed information may be printed to the window which can then be pasted here.  Your python version (`python --version`) would also be helpful.

Also, could you please try opening the RSS feed in a browser and downloading that episode with it?  If that also fails, then we know the problem is more general than gPodder.

**Comment by vossad01** [comment]
I believe @dbBerkeley 's replies were accidentally posted to https://github.com/gpodder/gpodder/issues/190#issuecomment-281224912.  I am replying here to try to return the discussion to the relevant issue.

Python 2.7.2 is rather old.  Please update to the latest 2.7.x version for better SSL support to hopefully resolve your issue. (coursera-dl suggests that at least 2.7.9 is needed).

**Comment by dbBerkeley** [comment]
I tried installing Python 2.7.13, but gpodder won't start now. It shows:
![image](https://cloud.githubusercontent.com/assets/24510958/23182208/9ec027c6-f82c-11e6-994f-382152b1c89c.png)

**Comment by dbBerkeley** [comment]
Oh, I see pygtk is different from Python. I'll try to find that.

**Comment by vossad01** [comment]
If you were were not successful in finding a download, there is a direct link to a PyGTK installer for Windows at http://gpodder.org/

**Comment by dbBerkeley** [comment]
OK - the problem is fixed. Thanks.
