### ISSUE TITLE
Add 'sync' command to gpo

### ISSUE THREAD

**Issue by yatahaze** [gpodder/gpodder#243]
I haven't been able to find a command to sync to devices via the command line. Could this be added?

**Comment by ToxicFrog** [comment]
Looking at the mailing list, it looked like this feature existed in gpodder ca. 2010, but got removed at some point. Unintentional regression?

This would be useful for me because I don't use gpodder to listen to the podcasts, just to download them, but the default filenames it downloads them to are a mess (and the ID3 tags aren't reliable either). I was planning to work around this by `gpo sync` to a local directory using an appropriate `device_sync.custom_sync_name`.

**Comment by elelay** [comment]
`gpo sync` was removed when the old sync code was removed but not reintroduced with the new sync code. Seems indeed like an overlook.

@ToxicFrog you should use/adapt the [rename_download](https://github.com/gpodder/gpodder/blob/master/share/gpodder/extensions/rename_download.py) extension to achieve what you want.

In its `on_episode_downloaded` method you get all the information you need to rename the downloaded file to whatever suits you.

**Comment by jcpeck** [comment]
@elelay @ToxicFrog - checking in on whether the gpo sync feature has been attempted/added.  If not, I am considering taking a stab at it.  Thanks for the update.

**Comment by elelay** [comment]
@jcpeck No, I didn't try. You should have a look at the download command: it has similar structure.
Good luck :-)

**Comment by jcpeck** [comment]
@elelay I have implemented the gpo sync command on a local branch named gpo-sync.  Just tried to push it but got permission denied.  How would you prefer to proceed with a pull request?

**Comment by elelay** [comment]
@jcpeck sorry I forgot to answer.
That's great news!
Yes, a pull request is definitely the way to go:
 - fork the gpodder repository (button on top of the page at https://github.com/gpodder/gpodder)
 - add your forked repository as a remote to your local repository (git remote add myfork git@github.com:jcpeck/gpodder.git)
 - git fetch myfork
 - git push -u myfork NAME_OF_YOUR_BRANCH
 - in your web browser, go to https://github.com/jcpeck/gpodder There should be a message about you just having pushed your branch and an offer to make a **new pull request**. Otherwise, navigate to the branch. There should be a button to create a new pull request somewhere.
 - save the pull request and I'll review it ;-)
