### ISSUE TITLE
gtk3: Delete key is captured for filtering rather than episode deletion

### ISSUE THREAD

**Issue by vossad01** [gpodder/gpodder#249]
## Steps to Reproduce 
1. Open gPodder.  Ensure you have at least one podcast and episode known to gPoddder.
2. Select an episode
3. Press the <kbd>Delete</kbd> key

## Old behavior
A dialog would prompt whether the downloaded episode should be deleted

## `gtk3` branch behavior
The list filtering box pops up with the following character entered: 

Noticed in trying to reproduce #208 

___
Edit: it appears other undesirable keys are also captured, such as <kbd>Tab</kbd>

**Comment by elelay** [comment]
closed by 447d658.
I first tried to add an accelerator to the action in menus.ui, but it didn't work as expected because it also captured Delete keys in the episode and podcast search entries.
So I added it to the window's `on_key_press` handler to check for focused entries. This seems silly but from what I understand of [gtk3 event handling](https://developer.gnome.org/gtk3/stable/chap-input-handling.html), the window's accelerators always prevail upon its widget's. Even for built-ins like Delete key!
Also noticed that Tab navigation was broken so added the `> 32` check in podcast and episode trees.
