### ISSUE TITLE
Resume playback

### ISSUE THREAD

**Issue by FryDay** [gpodder/gpodder#255]
I am currently unable to resume playback using anything but MPV (which I cannot use properly, since there is no MPRIS support). VLC with resume playback enabled will always start at the beginning, and then I have to seek to the last location I was at. Is this a bug or am I missing something?

**Comment by vossad01** [comment]
I _think_ gPodder's role in playback resume is only applicable if you are playing episodes with [panucci](https://github.com/xerxes2/panucci).

If you browse to the episodes on the file system and open them directly, does VLC resume playback work any differently?  If it does not, it is probably an issue with VLC and not gPodder.  Unfortunately, my experience with VLC resume playback is that it is nice when it works; but, more often than not it does not work.

**Comment by elelay** [comment]
It can be implemented using MPRIS2. See PR #262.
Testing is welcome...

**Comment by dovf** [comment]
If you enable the "MPRIS Listener" extension, then gpodder should become aware of the last played position for any episode played with a MPRIS capable player (VLC included). You can see this last played position in the Duration column in gpodder display (you may have to add that column to your view, IIRC it's not enabled by default).

In order to later *resume* at that position, I currently have my "Audio player command" set to
`vlc --playlist-enqueue --started-from-file --play-and-exit --one-instance-when-started-from-file --start-time %p %U`. This works for resuming a singe episode at the given position (the "%p" format specifier). There are, however, some quirks: it doesn't work if VLC was already open; conversely, the "start-time" argument is remembered by VLC for any episode played in this instance of VLC, so if you then enqueue another episode while VLC is still open, it will *also* start playing at said position rather than at the beginning, which is most likely not what you want. Nonetheless, this is the solution I currently use, I am just careful to work around these issue...

@elelay's PR looks interesting, and probably is a better solution... but I'm unable to test it at the moment (I haven't pulled a newer gpodder in quite a while, I see that since I last pulled it has moved to python3, so I'll have to do the upgrade more carefully sometime...)

**Comment by elelay** [comment]
@dovf actually gPodder master is still python2. You should be able to take the updated extension with your version of gPodder. I did not come up with a solution for multiple episodes either.

**Comment by dovf** [comment]
I'm on the gtk3 branch... :/

**Comment by vossad01** [comment]
@dovf If you are already running the `gtk3` branch, then you should already be positioned to try the PR.

This would be one way to get the code (assuming this repository is your `origin` remote)
``` shell
git fetch origin pull/262/head:pr-262
git checkout pr-262
```

**Comment by dovf** [comment]
Thanks, getting the code is not the issue...

It's just that I'm on the gtk3 branch as of about 3 years ago (actually
from not long after I submitted the MPRIS Listener extension), and updating
will necessarily involve some playing around (e.g., switching to python3).
Certainly doable, but gpodder is critical infrastructure for me ;) so I
want to do it carefully, and I just don't have the time at the moment...

**Comment by vossad01** [comment]
@dovf My bad, I hadn't realized that the `gtk3` branch existed much prior to PR #150 from last October.

**Comment by elelay** [comment]
[enqueue_in_mediaplayer.py](https://github.com/gpodder/gpodder/blob/master/share/gpodder/extensions/enqueue_in_mediaplayer.py) has landed in master and gtk3 branches. It's python2/3 compatible, but I'm not sure it works with old code. Best give it a try (copy it to a `gPodder/Extensions` folder). It adds a **Resume In** context-menu item on partially played single episode selection.
