### ISSUE TITLE
Release Process is not complete

### ISSUE THREAD

**Issue by adamvoss** [gpodder/gpodder#278]
I tried running through the [Release Process](https://github.com/gpodder/gpodder/wiki/Release-Process) to see what issues might be encountered if a release from the `gtk3` branch were attempted.  Even on the `master` branch there appeared to be  a number of issues suggesting that something is incomplete or outdated.

Examples:

No manpage for **gpodder**:
```
make manpage
LC_ALL=C help2man --name="Media aggregator and podcast client" -N bin/gpodder >share/man/man1/gpodder.1
/bin/sh: 1: cannot create share/man/man1/gpodder.1: Directory nonexistent
makefile:98: recipe for target 'share/man/man1/gpodder.1' failed
make: *** [share/man/man1/gpodder.1] Error 2
```

clean target appears to be missing in `setup.py`:
```
make release
python setup.py clean
running clean
find src/ '(' -name '*.pyc' -o -name '*.pyo' ')' -exec rm '{}' +
find src/ -type d -name '__pycache__' -exec rm -r '{}' +
find share/gpodder/ui/ -name '*.ui.h' -exec rm '{}' +
find: ‘share/gpodder/ui/’: No such file or directory
makefile:132: recipe for target 'clean' failed
make: *** [clean] Error 1
```

**Comment by thp** [comment]
Ideally we should make the release process as simple as pushing a tag and having CI build all the different release things (and just use the Github-provided tarball for source releases).

My proposal:

 * Can we automate UI testing of a simple first-time user subscribe situation? This would solve the "Test if gPodder works for normal and first-time use cases" task (we can also drop it)
 * The **Update src/gpodder/__init__.py** and **Update share/gpodder/credits.txt** could probably be put in a small Python script that a maintainer can run just before tagging a release (in `tools/`), this should probably also call `make messages` (to update the translation templates) and `make manpage` (which should probably be updated to not depend on `help2man` and either just update the version number and date using `sed` or have a small `help2man` replacement written using Python, so that it's always available, and we don't depend on `help2man` anymore).

I have some code that I use for building the Windows build (Python 2 + Gtk 2 only at the moment), maybe I can put that into the gPodder repository and make Travis CI or some other CI build the Windows releases as well and upload those to Github releases.

**Comment by vossad01** [comment]
I think all of those things are good ideas.  To a degree, they seem like longer term goals to me and many of the items could be their own issue.  I have synthesized #293 from your comments to try to give viability and tracking to this.

My hope for this issue issue is just to get steps that are usable/up-to-date currently even if they are manual.  At this point, I only know of one issue (#252) as outstanding before I would consider gPodder at a point where we could try to solicit broader testing of the `gtk3` branch.  I would like to be able to look into what deployment obstacles would arise if we did try to do that.

**Comment by adamvoss** [comment]
Is https://twitter.com/gpodder official?  Should tweeting be added to the [release process](https://gpodder.github.io/docs/release-process.html#release-noteswebsite-work)?

**Comment by thp** [comment]
That account was set up by somebody we don't know; it was reposting an RSS feed from the gpodder.org website that has changed since we moved to blogspot/blogger for the news. If we could regain that (inactive?) account that'd be great. However, instead of adding yet another step to the release process, I'd just hook it up with https://dlvrit.com or a similar service to repost blog entries.

**Comment by adamvoss** [comment]
> ag***********@s*************.***

**Comment by adamvoss** [comment]
> If we could regain  that (inactive?) account that'd be greatt (inactive?) account that'd be great

The best chance of that would be if we could make contact with who controls it (unless you happened to register gPodder as a registered trademark some where, in which case it would be easy).  The most I could get from Twitter was that the owner used an email address matching `ag***********@s*************.***`.

If contact is not possible, we  can appeal to Twitter and maybe get lucky, but probably would be told to make a different account. (`@TheRealGPodder` :upside_down_face:)

**Comment by adamvoss** [comment]
It looks like "harmattan" releases are not covered (just noticed them in history) have these ceased?

**Comment by thp** [comment]
Yes, "harmattan" isn't supported anymore, from http://blog.gpodder.org/2016/02/gpodder-390-helium-levitator-released.html:

"Starting from version 3.9.0, the N9 port is not supported anymore; the code is still available in the "harmattan" branch in Git if you need it or want to backport fixes yourself."

**Comment by elelay** [comment]
**3.10.1**
I have forgotten to do:
```
make messages
make manpage
```
before releasing. What's the consequence?

Also I should have waited for the travis build to finish (test was successful, luckily) before releasing.
I've smoke-tested gPodder on the mac manually before uploading the circleci build.

I've updated the website, but didn't post on the blog, nor sent a mail on the mailing list. I'll do it tonight if nobody beats me to it...

**Comment by thp** [comment]
Nothing, the manpages might have the wrong version (and if we would have added/removed parameters, those wouldn't be documented properly). The "make messages" is also not really that important these days, translators can just run it locally before they are doing the translations. Unfortunately, it doesn't look like we can really automate those.

We could have a build-time check in Travis that runs when building the release that fails if running `make manpages` changes the files, but that won't help in general, would just make sure we notice it /after/ tagging. Of course, we could move from generated manpages to manually-updated manpages, as I'm all for making the release process as simple as possible and with as few manual steps as we can :)

**Comment by elelay** [comment]
Now, we can run `make revbump VERSION=3.10.2` to update `__init__.py`, man pages, messages.
I've updated the release process accordingly, with everything I did or should have done, so I think the release process is complete.
