### ISSUE TITLE
Filenames in wrong format: eg 20170503103923-2-128.mp3

### ISSUE THREAD

**Issue by geejaytee** [gpodder/gpodder#297]
gPodder (running 3.9.3-1 on ubuntu 17.04), does not always update the file name, occasionally leaving them in the format
YYYYMMDDHHMMSS-2-{bitrate}.mp3
I can't see anything in the log files to see an error, just that it fails to rename the file once downloaded

**Comment by vossad01** [comment]
Thank you for reporting this issue.  Which podcast and episode did it happen with?  Are you able to provide steps to recreate this issue?

**Comment by geejaytee** [comment]
I can't provide steps which recreate the issue as it is intermittent. It happens after the usual hourly update of feeds, after downloading some episodes

**Comment by vossad01** [comment]
[Filename is derived from the download URL](https://github.com/gpodder/gpodder/blob/master/src/gpodder/util.py#L926-L960).  I am inclined to think the behavior you have experienced is by design and is the result of how the episode you downloaded was named on the server.

I am not entirely clear what the issue is, since the download folder is managed by gPodder.  If you need the file itself, gPodder's "Send to local folder" or "Sync to device" would be more suitable and will give a more human-friendly file name.

**Comment by geejaytee** [comment]
Files when downloaded by gpodder, get a ".partial" extension whilst downloading. This is then renamed to a ".mp3" when the download completes. I get a record of both files as the podcasts are downloaded into my Dropbox for access at multiple machines, so they both appear in my events log on Dropbox.

It does look like it is sporadic (so not reproducible), across different feeds. I've not checked whether they're all from the same webhost, but it would make sense as the filename was in the consistent format [Timestamp YYYYMMDDhhmmss]-[#channels]-[bitrate].

I'll close this off as not a gpodder bug.
