### ISSUE TITLE
[Feature Request] Favorites group or any kind of grouping or manual sorting.

### ISSUE THREAD

**Issue by Erquint** [gpodder/gpodder#306]
I've been waiting for this for many years now but it doesn't seem like the GUI is evolving at all.
Some podcasts I follow very closely — downloading every pod that comes out.
Others are just in my OPML in case I want to check out a specific relevant pod and for archival purposes.
I need to be able to sort them up into separate lists.

**Comment by vossad01** [comment]
gPodder has a "Sections" feature that allows you to group podcasts and may meet your needs.

Example:
![image](https://cloud.githubusercontent.com/assets/965439/26474309/dc93ecb2-4175-11e7-88da-1a2f5b0c19e1.png)

To access this feature:

1. Right click on a podcast
2. Choose 'Podcast settings'
3. Choose a section from the 'Section:' drop down (or use the '+' to add a new section)

**Comment by Erquint** [comment]
![qghmaft 1](https://cloud.githubusercontent.com/assets/4364856/26479014/e7742bc0-41d8-11e7-8666-a10ff86624f6.png)
Doesn't seem to be working as intended.
Win10.

**Comment by vossad01** [comment]
> Sorry for this non-issue then.
Sounds good.  Closing this issue.

> No option for batch section change though?

I don't believe so.  You could open an issue or submit a pull request.

> This is off-topic, but will passwords ever be hashed? It's not secure storing plaintext passwords.

Is this pertaining to passwords for authenticated podcasts or the gpodder.net credentials?  I am not sure what security concern you have; however, my guess is that unless someone submits a pull request, no, they will never be hashed.

_Hashing_ passwords is not an option for gPodder a password hash cannot be used for authentication, gPodder needs the original password.  gPodder could _encrypt_ passwords because an encrypted password can be decrypted for use.  However, if gPodder could automatically decrypt the passwords, an attacker with access to gPodder could just as easily decrypt the passwords, so any security gains were negligible to none.

If there is a real need for security, your options become:

* Encrypt passwords and protect with a master password 
  * Doable, but now users will be inconvenienced by needing to enter their gPodder master password when they need one of these passwords
* Make the OS responsible for securing the information
  * Correctly implemented, this can be secure (within the design of the OS's model); however, each platform will need to be implemented separately making inconvenient to implement.
* Don't use password-based authentication
  * This is out of gPodder's control
