### ISSUE TITLE
Support for Retina Screens under Mac OS

### ISSUE THREAD

**Issue by f-ewald** [gpodder/gpodder#339]
The binary version doesn't support retina screens and looks very pixel-ish.

**Comment by elelay** [comment]
Thanks for reporting!
This is a duplicate of #320. It will be fixed in next release (commit [here](https://github.com/gpodder/gpodder-osx-bundle/commit/cac0b9caaab08c6340bc43fbb33a24c0d93df086)). Meanwhile, you can fix it by adding following two lines to gPodder's `Info.plist` before the closing `</dict>`:
```
<key>NSHighResolutionCapable</key>
<true/>
```

**Comment by f-ewald** [comment]
Thanks that solves it.
