### ISSUE TITLE
[Win10] Undesired language.

### ISSUE THREAD

**Issue by Erquint** [gpodder/gpodder#342]
After a reinstallation of Windows 10 gPodder decided to be in Russian even though I fed it the old configuration files and everything.  
~~What gives? Please do not decide for the users the language they prefer.~~  
I haven't been asked for my preference or given a setting to change it.  
I need it in English.

**Comment by adamvoss** [comment]
Reading through some code, it looks like gPodder automatically chooses the language based on the contents of the following environment variables (in descending order of preference): 'LANGUAGE', 'LC_ALL', 'LC_MESSAGES', 'LANG'.  There is also fallback behavior in the event a language or translation is missing.

I think the most likely situation is that your environment has been configured in a way that makes Russian the preferred language.  I think configuring application language based on the OS is a valid design decision.  In the majority of cases, it would actually help users because they will only need to configure the language once rather than once-per-application.

**Comment by thp** [comment]
We could probably set these variables by looking at the Windows locale, to avoid such situations.

**Comment by Erquint** [comment]
The thing is: I have never been provided an option — not once, not twice, not on installation not in the configuration menu.  
Also every single option provided in various Windows configuration GUIs, including legacy ones, is set to prefer English. This is an issue for me, so I make sure it is always that way on every reinstallation.  
Make sure you are not going by ANSI codepage — it's a horrible practice, since that variable was never intended to describe language preference — it is there only for legacy compatibility.

**Comment by elelay** [comment]
The proper language should be picked since gPodder 3.10.2.
Please try with the latest 3.10.3 release.

**Comment by elelay** [comment]
@Erquint please reopen if it doesn't work for you
