### ISSUE TITLE
gPodder does not start up if the C locale is selected and certain extensions are active

### ISSUE THREAD

**Issue by ideasman42** [gpodder/gpodder#351]
With this command and Python3, loading gpodder gives an error.

Note that I found this by accident, the following command is just an easy way to redo.

```
export LC_CTYPE=C
gpodder
```

Gives the following error:

```
1508423397.708435 [gpodder.sync] WARNING: Could not find gpod
1508423397.708852 [gpodder.sync] WARNING: Could not find eyed3.mp3
1508423397.729301 [gpodder.log] ERROR: Uncaught exception: Traceback (most recent call last):
  File "/dsk/src/gpodder/src/gpodder/gtkui/main.py", line 3686, in do_activate
    self.window = gPodder(self, self.bus_name, core.Core(UIConfig, model_class=Model), self.options)
  File "/dsk/src/gpodder/src/gpodder/core.py", line 47, in __init__
    gpodder.user_extensions = extensions.ExtensionManager(self)
  File "/dsk/src/gpodder/src/gpodder/extensions.py", line 331, in __init__
    container = ExtensionContainer(self, name, config, filename)
  File "/dsk/src/gpodder/src/gpodder/extensions.py", line 201, in __init__
    self.metadata = ExtensionMetadata(self, self._load_metadata(filename))
  File "/dsk/src/gpodder/src/gpodder/extensions.py", line 236, in _load_metadata
    extension_py = open(filename).read()
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 189: ordinal not in range(128)

Traceback (most recent call last):
  File "/dsk/src/gpodder/src/gpodder/gtkui/main.py", line 3686, in do_activate
    self.window = gPodder(self, self.bus_name, core.Core(UIConfig, model_class=Model), self.options)
  File "/dsk/src/gpodder/src/gpodder/core.py", line 47, in __init__
    gpodder.user_extensions = extensions.ExtensionManager(self)
  File "/dsk/src/gpodder/src/gpodder/extensions.py", line 331, in __init__
    container = ExtensionContainer(self, name, config, filename)
  File "/dsk/src/gpodder/src/gpodder/extensions.py", line 201, in __init__
    self.metadata = ExtensionMetadata(self, self._load_metadata(filename))
  File "/dsk/src/gpodder/src/gpodder/extensions.py", line 236, in _load_metadata
    extension_py = open(filename).read()
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 189: ordinal not in range(128)
```

**Comment by elelay** [comment]
Thanks for the report.
BTW, if you use python3, you'll want to use the gtk3 branch.

**Comment by ideasman42** [comment]
I should have mentioned, I'm using the gtk3 branch.

**Comment by thp** [comment]
This is totally expected. The C locale doesn't define an encoding. Python falls back to ASCII. You need to use an UTF-8 locale. It is not just extensions, other parts of the system also depend on the locale (i.e. storing filenames with international characters will depend on a properly set locale).

The C locale should be reserved for 7-bit ASCII compatible encoding. This means that if your system runs on the C locale, all your Python files must be representable using 7-bit ASCII.

Note that Python has `-*- coding: utf-8 -*-` magic, that can be parsed by Python, see [PEP-263](https://www.python.org/dev/peps/pep-0263/). In those cases, it probably makes sense to read in extension module sources as binary (`bytes`) objects, and let the compile code take care of figuring out the encoding. But adding `encoding=` to the `open()` call as done in #352 is not the way to go.

What I could see being acceptable:

1. Reading in extension module source as `bytes` object using `rb` as file mode
2. Adding `-*- coding: utf-8 -*-` to the extension modules, so Python can pick that up

I'm not sure if that works, but could be a try. In general, I would advise against using a C locale, because it affects many parts of Python (filename encoding) that also leads to problems in other places.

**Comment by elelay** [comment]
As you know, [`_load_metadata()`](https://github.com/gpodder/gpodder/blob/gtk3/src/gpodder/extensions.py#L232) has to do some text parsing to extract metadata from the source code. I think it must do it on text not on bytes.

So I would favor:
  1.1 Read first 2 lines as `rb`, extract encoding as per PEP 263 `^[ \t\v]*#.*?coding[:=][ \t]*([-_.a-zA-Z0-9]+)` and `\xef\xbb\xbf` at the begining.
    This can be done on [bytes](https://stackoverflow.com/questions/5618988/regular-expression-parsing-a-binary-file)
  1.2 Re-read the extension as text in the detected encoding or ASCII if not explicit.

  2. Adding `-*- coding: utf-8 -*-` to the extension modules, as Thomas suggests.
