### ISSUE TITLE
gpodder is no longer seeing new episodes for a podcast.

### ISSUE THREAD

**Issue by lviolette** [gpodder/gpodder#465]
Coast to Coast AM is no longer downloading new episodes.  The last episode downloaded is from May 11th 2018.
When I check for new episodes, it always reports back with "No new episodes".

Anyone else having this problem?
gPodder 3.9.6
Windows 10.
It'd be nice if gPodder checked for application updates specific to the operating system you are running.

**Comment by elelay** [comment]
Can you post the podcast url ?
Thanks,

**Comment by lviolette** [comment]
Yes.  Here's the URL.  Unfortunately, it requires a login and password.

http://rss.premiereradio.net/coast/podcast.xml

If you need it, please pm me @ leo[dot]violette70[at]gmail[dot]com

**Comment by elelay** [comment]
No issue getting new episodes here (gPodder from git, Linux).
Have you tried the latest Windows release (3.10.3)?

**Comment by lviolette** [comment]
I have not. I moved away to another solution when 3.10.1.  I"ll try the 
latest version.

------ Original Message ------

**Comment by elelay** [comment]
Ok, thanks. Let me konw :-)

**Comment by cuboideum** [comment]
I have similar problems with two subscriptions not being updated by gPodder 3.10.9 running on Ubuntu 19.04. These might be related to the issue.

When the podcasts are newly added, either as URLs or through the 'gpodder.net search', gPodder finds the most recent episodes. Updating the existing subscriptions, however, always results in 'No new episodes', even if new episodes are available and also recognised upon deleting and re-adding the subscriptions.

The affected URLs are the following:

- http://podcast.hr2.de/derTag/podcast.xml
- http://podcast.hr-online.de/hr2_kinofilm/podcast.xml

I do not know if the problem is related to the issue as I cannot check the reported URL due to password constraints. Both of the URLs reported by me are also in xml. However, the following URLs are updated:

- http://www.ndr.de/podcast/podcast3002.xml
- https://www.deutschlandfunkkultur.de/podcast-hoerspiel.3655.de.podcast.xml
- https://feeds.br.de/hoerspiel-pool/feed.xml
- https://www.ndr.de/kultur/radiokunst/podcast4336.xml
- http://www.deutschlandfunk.de/podcast-wissenschaft-im-brennpunkt.741.de.podcast.xml

Thanks.

**Comment by elelay** [comment]
@cuboideum this was #640

**Comment by lviolette** [comment]
This is great news!  I've switched back to gPodder and confirmed that episodes are downloading again!
