### ISSUE TITLE
gPodder 3.10.2 fails to launch in Windows with inflateValidate error

### ISSUE THREAD

**Issue by vitaminj** [gpodder/gpodder#478]
Error dialog comes up on launch saying "The procedure entry point inflateValidate  could not be located in the dynamic link library c:\Program Files (x86)\gPodder\bin\libpng16-16.dll"
Was confused at first, because it should be now using all the local dlls it comes bundled with, and the error suggests some version mismatch somewhere?
Turns out I have an old zlib1.dll in my c:\windows directory for some commandline tools, and gPodder seems to prefer this over its local one, but that global zlib dll then tries to use the gPodder-local libpng and complains about the lack of inflateValidate due to mismatching versions.
Temporarily removing zlib from the Windows dir allows gPodder to start.
Could gPodder be modified to prefer local libraries at all times?

**Comment by elelay** [comment]
Thanks for the detailed bug report : I wouldn't have guessed what happens.

What happens is `zlib1.dll` is required by a python module (`binascii-cpython-36m.dll`) from the platform specific module directory `lib\python3.6\lib-dynload`.
As shown by procmon, it searches in : 
 1. C:\gpodder-3.10.3-portable\data\lib\python3.6\lib-dynload
 2. C:\Windows\SysWOW64
 3. C:\Windows\System
 4. C:\Windows
 5. C:\gpodder-3.10.3-portable\data\bin

![search_zlib](https://user-images.githubusercontent.com/222469/43079511-9859673c-8e8d-11e8-9a8a-b23b0227cd1d.png)

On your system it found `zlib1.dll` in `C:\Windows` and stopped there.

This is the case of a number of libraries (libbz2-1.dll, LIBEAY32.dll, libexpat-1.dll, libffi-6.dll, libgcc_s_dw2-1.dll, liblzma-5.dll, libpython3.6m.dll, libreadline7.dll, libsqlite3-0.dll, libwinpthread-1.dll, SSLEAY32.dll, zlib1.dll), as shown by this command:
```
 /C/gpodder-3.10.3-portable/data/lib/python3.6/lib-dynload > (for dll in $((for f in *.dll; do strings $f | grep '\.dll'; done)|sort -u); do if [ -e $dll ]; then   echo "OK $dll"; elif [ -e "../../../bin/$dll" ]; then   echo "KO $dll"; else   echo "SYS $dll"; fi;  done) | grep KO

```
I think this is due to [LoadLibraryEx(LOAD_WITH_ALTERED_SEARCH_PATH)](https://github.com/python/cpython/blob/3.6/Python/dynload_win.c#L221) in python base code.

Some of them (e.g. libpython3.6m.dll) are already loaded at the point platform modules are loaded, so no harm is done.
Following this, I have found a workaround: preload all libraries (could be libraries listed above, but better load everything so new dependencies will also work) in the `bin` folder: at the begining of `main` in `lib\python3.6\site-packages\gpodder_launch\gpodder.py`:
```
    from ctypes import cdll
    libs_dir = os.path.dirname(gpodder_script)
    for l in os.listdir(libs_dir):
        if l.endswith(".dll"):
            cdll.LoadLibrary(l)
```
It works, but it's not pretty.
What could also be done would be copying affected libraries to `lib/python3.6/lib-dynload` but would it create other problems?

Have you any clue on this?

**Comment by elelay** [comment]
MS documentation:
 [Dynamic-Link Library Search Order](https://docs.microsoft.com/en-us/windows/desktop/dlls/dynamic-link-library-search-order#alternate-search-order-for-desktop-applications)
[Dynamic-link library redirection](https://docs.microsoft.com/en-us/windows/desktop/dlls/dynamic-link-library-redirection) (doesn't work)

**Comment by elelay** [comment]
Actually, it was a known bug in [quodlibet](https://github.com/quodlibet/quodlibet/issues/2817) and [mingw64-python3](https://github.com/Alexpux/MINGW-packages/issues/3381)
@lazka, what do you think of the preload workaround?
Also posted on [python-dev](https://mail.python.org/pipermail/python-dev/2018-July/154750.html).

**Comment by lazka** [comment]
There also is this issue: https://github.com/Alexpux/MINGW-packages/issues/3343

I haven't had time to look more into this, but it came up there that calling https://docs.microsoft.com/en-us/windows/desktop/api/winbase/nf-winbase-setdlldirectoryw through ctypes might be the easiest workaround.

**Comment by elelay** [comment]
Yes, SetDllDirectoryW works using ctypes
```
    libs_dir = os.path.dirname(gpodder_script)
    from ctypes import windll
    windll.kernel32.SetDllDirectoryW(libs_dir)
```
It results in 

1. C:\gpodder-3.10.3-portable\data\lib\python3.6\lib-dynload
2. C:\gpodder-3.10.3-portable\data\bin
3. C:\Windows\SysWOW64
4. C:\Windows\System
5. C:\Windows
7. C:\gpodder-3.10.3-portable\data\bin (again)
8. any directory in the path

I'll try to put it in the launcher. Will you do the same for quodlibet?

**Comment by lazka** [comment]
> I'll try to put it in the launcher. Will you do the same for quodlibet?

Thanks for testing. I think I will :)
