### ISSUE TITLE
Windows Taskbar Progress Extension does not work

### ISSUE THREAD

**Issue by ghost** [gpodder/gpodder#483]
In the gPodder Setting under "Extensions" > "Desktop Integration" there's an option named "Show download progress on the taskbar". When I try to activate this extension, an error message appears telling me that the "Extension cannot be activated. Python module not found: comtypes" (see attached screenshot). I am using gPodder 3.10.3 portable on Windows 8.1 64 Bit. Where can I get/download this module and how can I install it into gPodder? 

![gpodder-taskbar-progress-error](https://user-images.githubusercontent.com/40357209/41533540-66f40e48-72fb-11e8-9ace-054a6be8c4f2.jpg)

**Comment by elelay** [comment]
Thanks for the clean bug report.
Yes, indeed : it doesn't work. AFAICT comtypes can't be installed in the msys2 based python we use now.
So another approach would be necessary, but I lack the expertise and interest to do so.
In the meantime, I can mark the extension disabled so that no other people stumble upon the problem as you did.

**Comment by technician77** [comment]
I'm not a programmer so it's not unlikely that I'm wrong but my msys2 installation offers `pacman -S  mingw-w64-x86_64-python-comtypes` but installing that didn't change the outcome. Using gpodder 3.10.11 on W10 1909.

**Comment by somePythonProgrammer** [comment]
On Python, I would really recommend using this library:
[LINK](https://github.com/somePythonProgrammer/TbProgressLib)

**Comment by auouymous** [comment]
@Marrib Can you test https://ci.appveyor.com/project/elelay/gpodder/builds/40353063/artifacts?

@technician77 There was a patch a month after you tested it that fixed a missing module issue. I don't know if the comtypes in #1126 will work or if mingw-w64-x86_64-python-comtypes is needed.

**Comment by Marrib** [comment]
Enabling the checkbox in the preferences works, the error message from my first post does not appear. But the download progress does not appear in the taskbar.

**Comment by Marrib** [comment]
> 
> 
> Can you try running gPodder in debug mode: maybe there is an extra error?
> See [this link](https://gpodder.github.io/docs/windows.html#debugging-gpodder-on-windows).

I did that and two major errors occur:

1. The download folder can't be created by gPodder (see Screenshot 1 and Log 1).
2. If I create the download folder manually, then the episodes do not download (see screenshot 2 and Log 2).

**Screenshot 1**
![Screenshot (1)](https://user-images.githubusercontent.com/40357209/129443458-62c6e352-bb79-472b-ae60-d25f627f947e.png)

**Screenshot 2**
![Screenshot (2)](https://user-images.githubusercontent.com/40357209/129443469-527df47c-ce0f-4462-82f4-b0e253774fa2.png)

**Log 1**
[2021-08-14 Log 1.log](https://github.com/gpodder/gpodder/files/6986297/2021-08-14.Log.1.log)

**Log 2**
[2021-08-14 Log 2.log](https://github.com/gpodder/gpodder/files/6986298/2021-08-14.Log.2.log)

**Comment by elelay** [comment]
Thanks for the screenshot and logs. Many *Vorgang wird nicht unterstützt* errors appear.
I don't know what's causing that. Maybe try again with the usual gpodder and send us latest logs (a directory named Logs next to Downloads in the gpodder home directory) ?

**Comment by Marrib** [comment]
> Many _Vorgang wird nicht unterstützt_ errors appear.

This means "Process (or action) is not supported" in English.

What I did was what you suggested: downloaded gPodder from [this link](https://ci.appveyor.com/project/elelay/gpodder/builds/40353063/artifacts) you provided, ran it with the argument "-v", enabled the Taskbar progress extension and then added one of the default podcasts "Linux outlaws". I did this on a fresh install of Windows 10 x64 21H1.

**Comment by Marrib** [comment]
Here are the steps I did and my findings:

1. I downloaded the regular/stable portable release, added the podcast "This American Life" and downloaded an episode. It all worked perfectly, see log: [regular.log](https://github.com/gpodder/gpodder/files/7008592/regular.log)
2. I downloaded the portable beta from the link you provided and added the same podcast "This American Life". Downloading an episode resulted in an error: see log [beta 1.log](https://github.com/gpodder/gpodder/files/7008606/beta.1.log) and screenshot
![beta 1](https://user-images.githubusercontent.com/40357209/129933541-fdbbbb84-3d76-457d-b5c7-80bbb9c96d86.png)
3. I created the download directory "/config/Downloads/This American Life" manually, because gPodder did not do it in step 2 automatically. Then I was able to downloaded an episode without an error, see [beta 2.log](https://github.com/gpodder/gpodder/files/7008625/beta.2.log)
4. I enabled the "Taskbar progress" extension in the preferences and started a download, but no download progress appeared in the taskbar, see [beta 3.log](https://github.com/gpodder/gpodder/files/7008646/beta.3.log)

**Comment by auouymous** [comment]
This should be fixed in 3.11.0, please re-open if this issue has not been resolved.
