### ISSUE TITLE
Download progress bars no longer show progress in gPodder 3.10.4 and 3.10.5 (Windows 10)

### ISSUE THREAD

**Issue by Platypus123** [gpodder/gpodder#547]
Using Windows 10. Upgraded from gPodder 3.10.3 to 3.10.4 (and now to 3.10.5) and the download progress bars on the "Progress" tab no longer show progress. It was fine in 3.10.3.
But the progress bars now just remain grey (as though no progress is being made) while the downloads are progressing and they stay grey even when the downloads complete.
In 3.10.3 they used to show progress in blue. I am no longer able to see which have completed and which are still downloading or haven't started yet.
And switching back to the "Podcasts" tab, the icon next to the episodes also used to be a progress bar, but now is just a static bar. Even when the episode download completes, it doesn't change to the completed icon (a green musical notes symbol) until you click onto a different podcast then back again.

Thanks for your help.

**Comment by Platypus123** [comment]
Not sure why, the problem has now gone away: progress bars now working normally.
The only thing I can remember doing that might have a bearing, is on the "Podcasts" tab, at the bottom the "check for new episodes button" was greyed out saying "no new episodes"; well clicking the  button to its right ("delete message" maybe, or whatever it is) maybe seems to have reset things.

Please close this ticket.

**Comment by Thlayli** [comment]
I'm still seeing this problem. I tried Platypus' fix and it didn't work for the current download. Perhaps it will work for the next podcast. The mini progress bar in the Podcasts list works, and I can check progress with the tooltip, but the one in the Progress tab stays grey. Using 3.10.7 installed on Windows 10.

**Comment by elelay** [comment]
Thanks for reporting!
Can you try running gPodder in debug mode, to gather more info about the issue ?
See [this link](https://gpodder.github.io/docs/windows.html#debugging-gpodder-on-windows).

**Comment by rasferret** [comment]
I've been seeing the same problems as the thread starter for some time now. I will try to gather some debug informations and will post them.

**Comment by rasferret** [comment]
[2019-03-20.log](https://github.com/gpodder/gpodder/files/2987946/2019-03-20.log)

**Comment by MattJEM** [comment]
I'm having the same issue in 3.10.8, also Windows 10.

**Comment by southvinement** [comment]
Same problem with version 3.10.9 on Windows 7 SP 1, 32-bit

This problem makes the program unusable for me.  I download Democracy Now and view it when eating breakfast.  I look at the progress bar on the Progress tab from across the kitchen when fixing my Raisin Bran and when I see the download completed I walk over to my computer and start the podcast.  The only way I determine a complete download now is to right click and see if Play is an option or to look at the file name extension in an explorer program and see if it is mp4 or partial.  I can't do that when fixing my cereal.

What is the purpose of having a Progress tab if you can't see progress in it?

**Comment by elelay** [comment]
I'll try to reproduce.
Do you download episodes manually or are they downloaded automatically when you refresh the podcast (if the later it's not something I use, so maybe the bug was overlooked)?

One thing that could help you would be automatically playback when the episode is downloaded. It can be easily done in an extension (save the  gpodder_ui object and call `playback_episodes` on it on episode downloaded when it's democracy now and it's between 6am and 8am ;-))

**Comment by southvinement** [comment]
In my normal mode of operation, a task in Windows Task Scheduler wakes up my computer and runs GPodder at a time when I think the podcast is ready and before I am ready to eat breakfast. G Potter downloads the podcast when it starts. My goal is to have the podcast ready and waiting on my computer when I sit down to eat breakfast and wake up the computer. I view the podcast on a TV attached to the computer.

This scheme works about three days out of five. When it works, it works well. On the other two days it fails for various reasons, including problems at the download site and my having turned the computer power off, which I do on weekends, and not having turned it back on for Monday. When it fails, I need to know that it is downloading and be able to view the progress bars. If it is not downloading, I need to know to figure out why is not downloading and take alternative action, such as a direct download from the site through my browser.

I can't play on download because usually I'm not there.

**Comment by Thlayli** [comment]
I haven't examined this issue in a while, so I'm not sure what the current
behavior is. I think the mini progress bar updates but the episodes tab
doesn't show progress. I have an RSS feed autorefreshing and downloading
episodes automatically. Everything always completes successfully when left
alone, I just can't see the progress if I happen to open the episodes tab
while something is already going. I'll update and test it again and report
back when I have a chance.

**Comment by elelay** [comment]
I can reproduce it with the Download Episode Autormatically setting alone (auto-refreshing doesn't impact it). It's only visible on windows. Most likely since 2016.

**Comment by elelay** [comment]
I've fixed the issue in 31e8de4. You can apply it right now by patching your gPodder installation to replace the whole `download_episode_list()` method.

**Comment by elelay** [comment]
You can also try latests builds here : https://ci.appveyor.com/project/elelay/gpodder/builds/26932472/artifacts
