### ISSUE TITLE
Drag and drop not working in 3.10.1 (Ubuntu bionic version)

### ISSUE THREAD

**Issue by catmatist** [gpodder/gpodder#554]
I used to routinely drag podcast episode titles to a file manager folder to copy the underlying downloaded audio file, but it stopped working. Usually it won't drag at all, but sometimes it will drag, but the file manager won't accept it. Also gPodder usually crashes a little later after I try this. As a work-around, "send to local folder" right-click menu item still works. All this is with Xubuntu 18.04.

**Comment by elelay** [comment]
Thanks for reporting.

This has been fixed in gPodder 3.10.2 and later versions. Unfortunately I don't know when it will be released under Ubuntu.

In the meantime, you can run gPodder from a git checkout or patch [/usr/lib/python3/dist-packages/gpodder/gtkui/main.py](https://github.com/gpodder/gpodder/blob/5629f57b400f12e88f035ab1c5d8643f383aa93b/src/gpodder/gtkui/main.py#L1021) to replace
```
selection_data.set(selection_data.target, 8, '\r\n'.join(uris))
```
with
```
selection_data.set(selection_data.get_target(), 8, '\r\n'.join(uris).encode())
```
