### ISSUE TITLE
error 22 invalid argument on seemingly random episodes

### ISSUE THREAD

**Issue by jadekitten** [gpodder/gpodder#591]
i'm on gpodder 3.10.6 on win10/x64  example  https://snag.gy/Po63GL.jpg  https://snag.gy/aznOev.jpg

**Comment by elelay** [comment]
That's a bug. Thanks for reporting.

**Comment by jadekitten** [comment]
debug console window output https://pastebin.com/QRm8HeZL I verified 3.10.6

**Comment by jadekitten** [comment]
hello????

**Comment by elelay** [comment]
Sorry: your answer fell into the cracks...
Thanks for the trace.

With it I was able to reproduce: the rss feed I tried it was http://lpotl.libsyn.com/rss, while you use http://feeds.soundcloud.com/users/soundcloud%3Ausers%3A137846288/sounds.rss

I shall be able to come up with a solution soon.

**Comment by elelay** [comment]
This is due to the server sending a wrong Content-disposition filename for some files:
correct: Episode 346: Mark Twitchell Part I - Favorite Duck of the Month
=> Content-Disposition: attachment;filename="LPOTL346FINAL_mixdown.mp3"
incorrect: Side Stories: Cannibal Corpse Rapture
=> Content-Disposition: attachment;filename="SS_CannibalCorpseRapture.mp3?dest-id=754182"

**Comment by elelay** [comment]
I've fixed it in

**Comment by elelay** [comment]
Fixed in 3.10.7
