### ISSUE TITLE
Powershell scripts for notifications

### ISSUE THREAD

**Issue by jskrdla** [gpodder/gpodder#632]
Is there any way to shut off the powershell notifications or change the location of where the powershell scripts are being generated? 
Our network security policy keeps flagging me for trying to run powershell from the AppData user folder.

**Comment by elelay** [comment]
Thanks for reporting!

Powershell notifications are run in [notification-win32.py](https://github.com/gpodder/gpodder/blob/master/share/gpodder/extensions/notification-win32.py).
By removing line 59 ```__mandatory_in__ = 'win32'``` you should get rid of them because the extension won't be loaded.
What version of gPodder are you running? portable or installer?
I would be interested in a way to reproduce it. Maybe first step would be a screenshot with the exact error message? Also, any error when running gPodder in debug mode would be a clue: see [this link](https://gpodder.github.io/docs/windows.html#debugging-gpodder-on-windows).

Maybe it's something that could be easily fixed. 
For instance, try changing line 143 to set the working  directory to `c:\`: add `cwd='C:/'` after `powershell,`
```
            subprocess.run([powershell, cwd='C:/',
```

**Comment by jskrdla** [comment]
Thanks @elelay for getting back to me!. I played around with it over the weekend and figured out if I just pass out of the on_notification_show method, that would stop the messages, but I've implemented your change and it seems to be working. I'm a newbie to python, so I just have to stumble around it at times.

The PS scripts are just notifications ("Error while updating [feed]:..." or "404 file not found" or "Downloading 4 new episodes" messages).

If not for our network policy, I wouldn't have even noticed. I'm pretty sure that it started happening in 3.10.4, and because of that I've been running 3.10.3 until the recent Youtube issue. I'm currently on 3.10.8 from the windows installer.

If you still want a debugger file, I can try to get one of those for you. Just let me know.

Thanks again for your response!

**Comment by elelay** [comment]
Great to know that it fixed it for you. Is `cwd=gpodder.prefix` working as well as `cwd='c:/'`? If so I'll add it to notification-win32.py.

**Comment by jskrdla** [comment]
I didn't try changing the cwd. I only removed the __mandatory_in__ = 'win32' line.

**Comment by elelay** [comment]
OK. Then I'm not changing anything.
Thanks,
