### ISSUE TITLE
moving forward with gpodder-core

### ISSUE THREAD

**Issue by elelay** [gpodder/gpodder#650]
# gPodder codebases

We've got gpodder/gpodder (gpodder for short), gpodder/gpodder-core, gpodder/gpodder-ui-qml and gpodder-sailfish.

gpodder-core + gpodder-ui-qml is a rewrite of gpodder targetting the sailfish app (gpodder-sailfish).
It's written in python3, with code bearing resemblance to gpodder's code at the time, without gtk3 entanglements. It has some features gpodder only added lately (eg. paged rss feeds) and clean code, without cruft from the years.

Meanwhile, gpodder has been migrated to python 3 and continued evolving over the years (more cruft added, corner-cases addressed, bugs fixed, etc.). gpodder-core stayed as it was in 2016, gpodder-sailfish was dormant.

Now @Keeper-of-the-Keys, @carmenfdezb and @sfbg are making great progress on reviving the sailfish app. But they encounter bugs or missing features in gpodder-core, fixed in gpodder.

# Differences

*here a pelemele of differences I noticed as I browse gpodder-core vs gpodder code*

## Code
`gpodder/src/*.py` and `gpodder-core/src/*.py` have similar modules.

gpodder-core uses minidb for model storage, gpodder uses its own schema.py  (+ own version of minidb for mygpo local storage).

gpodder's feedcore has special handling of different http errors, not seen in gpodder-core.

plenty of subtle code changes

gpodder-core has the Registry: a powerful hook engine. gpodder has Extensions, with different hooking possibilities and more actual extensions.

## Features

*please correct me if I'm wrong, add info here*

gpodder has features irrelevant to sailfish: multi-platform, sync to mp3 player, mpris

### useful features not in gpodder
 - ~~paged feeds  (implemented but not released)~~
### useful features not in gpodder-core stack
 - opml import?
 - ~~actual extensions (rename, tag, transcode)?~~
 - mygpo (gpodder.net integration) to synchronize with desktop instance?

## Translations
gpodder has many translations (many dormant) using gettext tooling, gpodder-sailfish has fewer (but growing) translations using Qt tooling. gpodder-core has bin/gpo translations using gettext tooling but some messages are not translated (mainly [src/gpodder/download.py](https://github.com/gpodder/gpodder-core/blob/master/src/gpodder/download.py#L836)).

# What shall we do?

I see 3 approaches:
 1. keep gpodder and gpodder-core separate. Reimplement missing features or bugs in gpodder-core as need be, inspired by gpodder when relevant;
 2. bring gpodder-core up to speed quickly, base a new gpodder-ui-gtk3 on it;
 3. create a new gpodder-core from current gpodder, and rebase gpodder-ui-qml on it.

This is really 2 approaches: keep carrying on or break things. If we break things, we have to choose which one is the base.

Do you see other routes?

# @elelay's take on it
Since I created the issue, I'll talk first :-)

It is better to have only one codebase for common behaviour, to pool our efforts and to do things only once. The gpodder-core stack has the cleaner architecture, so I would be inclined to choose approach 2. But moving to a gpodder-core stack for the desktop app is a huge undertaking and I'm not willing to do it alone. It's likely to create regressions for users (users already suffered in the switch from gtk2 to gtk3).

**let's discuss this** @thp @Keeper-of-the-Keys, @carmenfdezb, @sfbg, @auouymous (and anybody interested).

**Comment by sfbg** [comment]
@elelay fantastic initiative and write-up. Thank you.
I think from a pure architectural point of view, it is quite clear what is the cleanest way to do it: set up one gpodder-core that serves all other platform specific projects. 
But this is the theory. In practice, we have to consider what is the cleanest way forward given the real world constraints, mostly **budget** (in invested time and effort) and **available talent**.

So, we would have to get an understanding of who of the currently active contributors is
- actually technically capable of doing required work
- ready to invest how much effort

For that purpose, I'd kindly ask the active colleagues here to honestly answer these two questions, and then we can consider the most feasible option currently.

Let me go first:
- I do not consider myself proficient enough to contribute much directly to the gpodder-core activities. My interest is mostly in the UI/UX part, specifically on Sailfish.
- I can invest 4-5 hours a week (mostly for improving the Sailfish release, but also testing of core topics)

**Comment by Keeper-of-the-Keys** [comment]
@elelay great summary!

I agree that ideally we should have a single gpodder-core to rule them all.

That being said I have not yet familiarized myself enough with the current version and other then looking at backporting certain features have not looked at the main gpodder at all so it is hard for me to say which one should be chosen.
OTOH I also have no emotional attachment to anything and will try to assist with whatever path you choose.

**Comment by auouymous** [comment]
I strongly dislike python which prevents me from writing code in it. Bugs motivate me enough to fix them.

Replacing gpodder with gpodder-core would be ideal but would also take a while with limited help. And during that time gpodder is likely to get additional features/fixes that must be ported to gpodder-core. Forgetting to port something would cause a regression when the switch over happened. Users of only gpodder are less likely to help (as much) with a conversion they wouldn't be able to use for quite some time.

But breaking down the conversion into smaller tasks and implementing them in gpodder and gpodder-core simultaneously might be easier and could happen incrementally over time. Regressions could be fixed as each task is completed, instead of a flood of issues landing all at once when gpodder was eventually replaced with gpodder-core. Could gpodder-unified-core be created and used by both gpodder and gpodder-core? It could slowly grow over time while the other two shrink. Separating gpodder from gtk3 would be a logical first step.

If someone were to split each step into small issues, it might make it less overwhelming and attract more contributors (including those who hate python).

**Comment by thp** [comment]
Some historic notes just for old time's sake, and to explain (for those interested) how it came to be that the Desktop codebase and the Sailfish codebase diverged:

gPodder started out as a Linux-only app, then (I don't remember the exact chronological order) got ports to Windows, macOS, Maemo 4 (pen-based Hildon UI, which is based on Gtk) and then Maemo 5 (finger-based Hildon UI, which is still based on Gtk, but different from Maemo 4). After that, it was ported to MeeGo 1.2 Harmattan (Qt4-based QML UI) and then to Sailfish OS.

If you look at the lines of code over time [here](https://www.openhub.net/p/gpodder/analyses/latest/languages_summary) you can see the big spike in August 2009, which was when Maemo 5 support was added (more or less copy existing UI bits + code and adapt them to the new UI elements). By that time, there were 3 UIs (Desktop, Maemo 4, Maemo 5) and those had partially shared and partially duplicated/customized code in the same repo.

At some point later, Version 3.0 ([November 2011](http://blog.gpodder.org/2011/11/gpodder-300-397d-released.html)) was released with the Maemo 4 and Maemo 5 code removed (the Maemo 4/5 support was still maintained in the 2.x branch for some times, but mostly bugfix-only). Between November 2010 and November 2011, the codebase shrunk due to the removal of those two interfaces (mostly the XML UI stuff removed, but there was also separate code for each UI). During that time, of course a new mobile interface (MeeGo 1.2 Harmattan) came around, this time using Qt4+QML using PySide, which again let the codebase grow (this time, the UI code was totally new, whereas with Maemo 4 and Maemo 5 some code could still be shared with the Gtk UI).

As an interesting side note, due to my focus on mobile platforms, gPodder 3 initially got the device sync (think iPod and MP3 player, where you attach the device to your computer, copy the podcast files, then detach the device and play the files on the go) removed. This was eventually added back. It's a similar situation with gPodder 4 (gpodder-core), but of course there could be something layered on top of it for device sync.

Of course, MeeGo 1.2 Harmattan also died off quickly, and in 2013, Sailfish OS, which was based on Qt5+QML came up. At this point, I thought it makes sense to modularize gPodder and instead having all UIs in a single repo, split the UI from the core. There are some thoughts on this documented here:
http://blog.gpodder.org/2014/03/gpodder-4-vs-gpodder-3-release-notes.html

The wiki page linked from there is available on archive.org:
http://web.archive.org/web/20131120091114/http://wiki.gpodder.org/wiki/Cuatro

So there were some even more drastic ideas, like doing (parts of) the core in C++. What we ended up with was "gpodder-core", the Python 3-based codebase we're seeing now, and UIs on top. The plan at that point was to eventually arrive at a "gpodder-ui-gtk" that builds on top of "gpodder-core", but that obviously never happened. In fact, if you look at the repos at https://github.com/gpodder, there are even some packaging repos:

https://github.com/gpodder/gpodder-windows
https://github.com/gpodder/gpodder-android
https://github.com/gpodder/gpodder-bb10
https://github.com/gpodder/gpodder-sailfish

All those built on top of the "reference" QML UI: https://github.com/gpodder/gpodder-ui-qml

In case of Sailfish OS, it built also on top of the reference QML UI (shared some model code with it), but added its own, Sailfish OS-specific UI, for BB10, Android and Windows, the UI was the same. I guess at some point there was also the idea to just base the "Desktop UI" on top of QML, some parts of this are here:
https://github.com/gpodder/gpodder-ui-qml/tree/master/desktop

But around that time, I had spent about 10 years or so on the project and decided to do something else instead, so some of the planned things never panned out. I have head of some people who use gPodder only via CLI already upgraded to gpodder-core, but all other gpodder-core use cases (e.g. Android, Blackberry 10) have mostly died off (in case of BB10, the OS went away, in case of Android, I started using Google Podcasts a year or so ago, and now that it has a sleep timer, it works Good Enough for me...).

With that said, some "good" things that came out of gpodder4/gpodder-core were for example the podcastparser module (https://github.com/gpodder/podcastparser) that we eventually started using in gPodder 3 as well (https://github.com/gpodder/gpodder/pull/170). This is not only more suited for parsing podcast feeds (and easier to extend to add support for things like paged feeds), but is also SIGNIFICANTLY faster than the old "feedparser" module (this was one pain point on mobile, that parsing feeds really took up 100% CPU on mobile phones back in the day for a few seconds due to feedparser being suboptimal, which was also one of the inspirations for thinking about doing the core in C++ -- I did a post about this on Google+, but alas, that service is long since gone).


For some more historic trivia:

2005-05-01: [gPodder 0.1](https://sourceforge.net/projects/gpodder/files/source/gPodder-0.1-source.tar.gz/download) (written in Java, using Gtk bindings; intended to eventually sync them to my new iPod Mini 2G, using [Gtkpod](http://www.gtkpod.org/index.php?title=Home))
2005-09-03: [gPodder 0.3](https://sourceforge.net/projects/gpodder/files/source/gpodder-0.3.tar.gz/download) (re-written in Python - my first Python project -, as Java on Linux was hard to deploy back in the day, 505 lines of Python code + 886 lines of Glade XML for the UI; do NOT look at the code, it's ugly, fully of security holes and generally an exhaustive demonstration of bad practice)
2005-06-28: For some context, in the "real world", Podcasting feature [added to iTunes only then](https://www.macrumors.com/2005/06/28/itunes-4-9-now-available/)
2006-02-22: Tuomas Kuosmanen [suggests porting gPodder to Nokia 770](http://web.archive.org/web/20060518213619/http://www.tigert.com/archives/2006/02/22/random-thoughts-again/)
2007-01-31: Mikka Leppinen [ports gPodder to Maemo 4](https://garage.maemo.org/forum/forum.php?forum_id=645)

..and that was more or less the start of the countless mobile ports.

**Comment by thp** [comment]
My lazy, old, grumpy take on the issue at hand:

It's totally fine if there's a bit of a split between "Desktop" gPodder and "Mobile" gPodder. Those parts where there are pain points cross-porting whenever something changes (e.g. YouTube fixes) could be rewritten to use e.g. "youtube-dl" as a dependency.

ad extensions: "rename", "tag" and "transcode" are not needed on Sailfish OS, the playback UI is part of gPodder and IIRC the system ships with all codecs used in podcasts. Those extensions are mostly useful on the Desktop only if you sync to a device that only reads tags (or only file names) or only understands certain formats. Of course, some people believe that transcoding downloaded MP3s to OGG Vorbis files will make the world a better, free-er place [ignoring the fact that the MP3 patents expired AND the added digital generational loss from transcoding from lossy to lossy]. Or even worse, transcoding downloaded MP3s to FLACs, because "somebody read on the internet that FLAC is better quality" [ignoring the digital generational loss introduced by the MP3 encoding] 🙄

In fact, there could be a fourth option:
4. Combine gpodder-core, gpodder-ui-qml and gpodder-sailfish into its own thing

And then maintain "desktop gpodder" and "sailfish gpodder" as two separate things, maybe slowly approaching a point where both are similar enough that they can start sharing more code, either by pulling common parts out (like we did with podcastparser).

I'm not going to be the one doing the work, so it's not my call to make, but in my experience, instead of "investing 4-5 hours a week" to shuffle around the code just to make it all end up in a single place isn't really time well spent (even though I spent lots of time doing just that in the past, these days I don't think it's a good usage of one's time).

Better to spend the time improving the app for users or doing something completely different with the time saved.

Another upside of keeping those things separate: Contributors usually either use the Sailfish app or the Desktop app, not both. If there are two repos, Sailfish contributors won't break (and won't need to regression-test) the Desktop app, and Desktop contributors won't break (and won't need to regression-test) the Sailfish app. Especially true for "fly-by" contributors with a single patch.

But that's just my two cents :)

**Comment by elelay** [comment]
Thanks Thomas for the historical perspective as well as your insightful take on the issue at hand :-)

**Comment by Keeper-of-the-Keys** [comment]
Thanks Thomas that was very enlightening and also thanks for trusting us with your baby.

Based on this I would say that whatever files that gpodder-sailfish is using from gpodder-ui-qml should just be integrated directly with gpodder-sailfish since it really doesn't make sense that reference implementations and "real world" application code mix and thus have their changes interact the way they do now.

I don't know how far apart gpodder-core and gpodder3 are but it does make sense to me to keep gpodder-core seperate from the UI with the caveat that stuff in gpodder-core should probably not be outputting strings to the user ever, the whole point is that that is core stuff and UI is handled by whatever project is using it.

**Comment by elelay** [comment]
> "rename", "tag" and "transcode" are not needed on Sailfish OS

I see. People also like to normalize and speed up their podcasts, but it is also possible at playback. So no current gpodder extension would be useful in gpodder-sailfish.

What about opml, mygpo? Other things (there is a discussion about html shownotes)? 

> 4. Combine gpodder-core, gpodder-ui-qml and gpodder-sailfish into its own thing

@Keeper-of-the-Keys suggests merging only gpodder-sailfish and gpodder-ui-qml. This could be very convenient for sailfish maintainers.

> If there are two repos, Sailfish contributors won't break (and won't need to regression-test) the Desktop app, and Desktop contributors won't break (and won't need to regression-test) the Sailfish app.

That's true. On the other hand, merging would be a good reason to all work together on the same thing. But this could be achieved differently, maybe by focusing on the same features around the same time for instance (just an idea).

> Better to spend the time improving the app for users or doing something completely different with the time saved

Big yes! It's taunting when looking at those 2 versions of the code to see them *that close* but I can imagine how quickly we would drown in the details when merging them.

Regarding user visible improvements, I've been working on and off on a youtube-dl extension, but have yet to flesh it out. Use case is to allow downloading audio-only versions of podcasts. My todo list also contains finishing the opds extension, refactoring so subscribing and refreshing are interruptible, accessibility on Windows/macOS (that last one is a pipe dream).

Regarding:
**actually technically capable of doing required work** 
I don't know the sailfish stack, don't own a jolla phone, never run it in the emulator, but would be interested to give it a go sometime. OTOH the gpodder codebase is pretty familiar now.
**ready to invest how much effort** 
usually I squeeze 1 day or 2 during holidays + the occasional rainy Sunday. Else 1-2 hours a week, looking at issues and fixing small bugs. A bit more when doing a release.

**Comment by Keeper-of-the-Keys** [comment]
There is an open bug for allowing podcasts to be played back at higher speeds on sailfish.
The built-in player does allow for speed up but the results vary and it lacks pitch correction so a plugin that does this ahead of time may be very interesting (although changing speed on the fly is really cool too) but I think I'm risking taking things OT here.

I must admit that I don't know what plugins currently exist because I basically only played with the desktop version of gpodder once when I was trying to see if soundcloud stuff worked in the main gpodder but it is something worth looking into :).

**Comment by sfbg** [comment]
> It's taunting when looking at those 2 versions of the code to see them _that close_ but I can imagine how quickly we would drown in the details when merging them.

This. 

The more I think about it, the more I am also inclined to say that given the circumstances, we should abandon the "high road" in terms of architecture and concentrate on what is achievable: working on and continuously improving the Sailfish and Desktop versions in parallel, optimally, in a collaborative fashion.
Judging from this productive discussion, this might work out pretty well.

For the record, I am also for integrating gpodder-ui-qml into gpodder-sailfish in order to streamline development of the latter.

@thp, big thank you for the historical recap. As an old fan, it was an absolute pleasure to read :)

**Comment by carmenfdezb** [comment]
Sorry, I don't know what to say because I don't have enough knowledge for that hard work

I agree with @sfbg, maybe the best option is working on Sailfish and Desktop apps separately but in a collaborative way.

>     * opml import?
Some work is done:  https://github.com/gpodder/gpodder-ui-qml/commit/8aab9adb4d9e0b4d669e44824d2e193f7278d480

**Comment by elelay** [comment]
> Some work is done: gpodder/gpodder-ui-qml@8aab9ad
so this is feasible, but should be adapted for the sailfish ui, right?

**Comment by elelay** [comment]
We have reached an agreement not to engage in anything drastic, but to integrate gpodder-ui-qml into gpodder-sailfish as useful (feel free to do it at the best time, no need to hurry).
So I'm closing the issue now.

Thank you all for your input! Keep up the great work :-)

**Comment by carmenfdezb** [comment]
> 
> 
> > Some work is done: [gpodder/gpodder-ui-qml@8aab9ad](https://github.com/gpodder/gpodder-ui-qml/commit/8aab9ad)
> 
> so this is feasible, but should be adapted for the sailfish ui, right?

Yes, I think so. I will try to implemented it
