### ISSUE TITLE
Search for new episodes on startup extension broken in 3.10.10

### ISSUE THREAD

**Issue by omoknen** [gpodder/gpodder#683]
After upgrading the extension "Search for new episodes on startup" no longer works.
A manual "Check for new episodes" work, and my 30 min check does work.

Is there something I can check in a configuration file etc...  I ran the cmd in -v and I did not see anything wrong.

[omoknen-log-gpodder.txt](https://github.com/gpodder/gpodder/files/3667385/omoknen-log-gpodder.txt)

Thank you

**Comment by elelay** [comment]
This is something I changed just before the release (in commit d5118d9).
Maybe it doesn't

**Comment by elelay** [comment]
Thanks for reporting!

This is something I changed just before the release (in commit d5118d9) and it was poorly implemented, resulting in the extension not working if there is no partial download.
I've just fixed it in commit ec315df, which you can apply manually if you want.
Otherwise, wait for a 3.10.11 bugfix release coming shortly...

**Comment by elelay** [comment]
3.10.11 has been released.
