### ISSUE TITLE
Feed does not work

### ISSUE THREAD

**Issue by ngorel** [gpodder/gpodder#688]
This feed does not work on my Ubuntu System: http://omegataupodcast.net/nurDeutsch.php, works with Antennapod and podget. Thank you.

**Comment by auouymous** [comment]
I was able to subscribe to it and download an episode on Gentoo Linux with version 3.10.10. Do you get an error dialog or a stack trace in console? What versions of gpodder and podcastparser do you have?

**Comment by ngorel** [comment]
From today on it is working here too. Earlier i got error reports (version 3.9.x):
![omegat](https://user-images.githubusercontent.com/56222117/66308914-8ca2cb00-e908-11e9-8da1-cd7e3e3bdd50.jpeg)
I have Ubuntu 16.04, and the latest version of gpodder 3.10.11.

**Comment by auouymous** [comment]
When sites are undergoing maintenance they serve a single HTML message page for all paths. And temporary problems with the site or their php code can return various 50x HTML error pages. Clicking that blue link would have shown the error while the problem was happening. There is nothing gpodder can do about it, except maybe detect the "got HTML" message/exception and provide a better error message that indicates the site is down.

**Comment by elelay** [comment]
Thanks for reporting!
Indeed, there is nothing more gPodder can do. It displays that it got html instead of the expected rss.
There can be many reasons for getting html. Maybe the domain expired and it's advertisement page, or the feed was removed, or moved and a "nice" html page with instructions to update the subscription is shown, etc...
