### ISSUE TITLE
Can't update podcast

### ISSUE THREAD

**Issue by BeBiMa** [gpodder/gpodder#694]
I have added the podcast URL [https://www.swr.de/~podcast/swr1/bw/hitparade/SWR1-Hitparade-Der-Podcast,artikel-swr1-hitparade-der-podcast-100.xml]( https://www.swr.de/~podcast/swr1/bw/hitparade/SWR1-Hitparade-Der-Podcast,artikel-swr1-hitparade-der-podcast-100.xml) to gpodder.
The first access functions. But if I come back to gpodder the special character  ',' is changed to '%2C'. A update fails because this "escape char" seems to be unknown to the server.
'~' was changed to %7E, which is a legal escape and handled right.

The stored URL is "https://www.swr.de/%7Epodcast/swr1/bw/hitparade/SWR1-Hitparade-Der-Podcast%2Cartikel-swr1-hitparade-der-podcast-100.xml".

**Comment by auouymous** [comment]
Technically, that server is doing it wrong and should decode all characters, or at least all special characters it uses. You should report the issue to that site.

Gpodder could decode escape characters before sending but it would need to ignore %20 because spaces are not valid in HTTP requests. Decoding will also cause other issues if a query string is used that contains pre-encoded characters that change meaning if decoded, such as ampersand.

**Comment by BeBiMa** [comment]
Ok. I assumed this.
I'll try to contact the server owner.
