### ISSUE TITLE
Undefined Entity error

### ISSUE THREAD

**Issue by GregBed** [gpodder/gpodder#696]
I am trying to add a podcast to gpodder. Gpodder recognized the URL but returns the following error:
Some podcasts could not be added to your list: http://feeds.burner.com/ctc: Could not parse feed: <unknown>: 435:37: undefined entity. 
This is a fairly popular podcast, Christ the Center. This is there website: https://reformedforum.org/programs/ctc/. 
I had been using iTunes but am migrating away from it now that it is being phased out by Apple. Never had a problem with iTunes and this podcast.
Thanks

**Comment by auouymous** [comment]
For anyone else looking into this, the feed is https://reformedforum.org/programs/ctc/feed/.

The problem is that the site doesn't wrap text containing &amp;nbsp; in a CDATA tag. It is not valid XML or a valid RSS feed. Some programs ignore specs and that allows sites to be lazy and remain broken. You should report this to that site.

**Comment by GregBed** [comment]
Thank you.

 

Gregory P. Bednarchik CPA

856-235-8440 x110

 

Secure Document Exchange by CPA SafeMail:

Send Me Secure Files                         Client Drop Box <https://portal.safesend.com/29891841/DropOff.aspx?DropEmail=greg.bednarchik@verizon.net>
