### ISSUE TITLE
Add episode menu option to download with youtube-dl extension

### ISSUE THREAD

**Issue by auouymous** [gpodder/gpodder#718]
http://borg.qzx.com/files/gpodder-718-add-episode-menu-option-to-download-with-youtube-dl.patch

When manage_downloads is unchecked, the youtube-dl extension will add an episode menu option to download with youtube-dl. Any episode that fails to download with gpodder's code can be manually attempted via the youtube-dl extension.

**Comment by auouymous** [comment]
This fails if no successful or failed downloads have happened before using the menu option. When a download task exists, it is able to run it before unregistering the custom downloader. Downloading a selection of episodes would also fail on some of them if not enough download tasks existed to handle all of them. I don't know how to fix this, yet.

**Comment by elelay** [comment]
Good idea but it seems a bad implementation choice: what happens if new episodes are automatically downloaded while the custom downloader is registered? They will wrongly use youtube-dl, right?

Also you should check for the presence of a downloaded file for the episode to choose to return or not the action item.

Finally, a blank line is missing between methods.
