### ISSUE TITLE
tagging extension broken in 3.10.12

### ISSUE THREAD

**Issue by tordenflesk** [gpodder/gpodder#737]
Since upgrading to 3.10.12 all tags get removed, with this error in the logs:

2020-01-27 07:29:46,109 [gpodder.extensions] ERROR: Error in C:\Program Files (x86)\gPodder\share\gpodder\extensions\tagging.py in on_episode_downloaded: "'subtitle' is not a valid key"
Traceback (most recent call last):
  File "C:\Program Files (x86)\gPodder\lib\python3.8\site-packages\gpodder\extensions.py", line 83, in handler
    cb_res = callback(*args, **kwargs)
  File "C:\Program Files (x86)\gPodder\share\gpodder\extensions\tagging.py", line 200, in on_episode_downloaded
    self.write_info2file(info, episode)
  File "C:\Program Files (x86)\gPodder\share\gpodder\extensions\tagging.py", line 278, in write_info2file
    audio.write_basic_tags(self.container.config.modify_tags,
  File "C:\Program Files (x86)\gPodder\share\gpodder\extensions\tagging.py", line 99, in write_basic_tags
    audio.tags['subtitle'] = self.subtitle
  File "easyid3.py", line 229, in __setitem__
mutagen.easyid3.EasyID3KeyError: "'subtitle' is not a valid key"

**Comment by tordenflesk** [comment]
Downgrading to 3.10.11 restores expected function

**Comment by AntonelloA** [comment]
@elelay Sorry for the inconvenience, but I found that the problem is in the Mutagen extension.
When I first tried to add subtitle to the mp3 tags (about 1 year ago) I recall I had to manually add the "mutagen" folder (taken from github) to folder "\gPodder\lib\python3.7", because a clean installation of GPodder didn't have that extension.
Now GPodder includes that extension (under "\gPodder\lib\python3.8\site-packages"), but if I manually add the old "mutagen" folder (see attachment) to a clean installation of GPodder 3.10.12 under "\gPodder\lib\python3.8" everything is working fine, even the new "subtitle" tag.
Can you please try to fix this problem? I'm not an expert in Python programming
Thanks
Antonello
[mutagen.zip](https://github.com/gpodder/gpodder/files/4129561/mutagen.zip)

**Comment by elelay** [comment]
I don't understand: your version of mutagen has following contents at [easymp3.py:486](https://github.com/quodlibet/mutagen/blob/master/mutagen/easyid3.py#L486):

```
    "COMM": "comments",
    "TIT3": "subtitle",
```

contrary to ANY VERSION in mutagen repository, which has:

```
    "TIT3": "version",
```

I've asked on mutagen's side: https://github.com/quodlibet/mutagen/issues/438

**Comment by elelay** [comment]
TIT3 and COMM are indeed for subtitle and comments in ID3v2 spec...

**Comment by AntonelloA** [comment]
Now that you're pointing at it, I remember I also had to modify easymp3.py inside the "mutagen" folder.
Sorry that I have forgotten that, but the reason was that I needed a new tag/frame, because for some reason "subtitle" is visible in Windows Explorer, but not inside VLC Player, and the opposite is true for "comments" tag (see attachments). So I found ID3v2 specs, and added the "COMM" frame.
Sorry again for any inconvenience, and for wasting your time, but I had really forgotten all these steps.
Antonello
![Windows Explorer](https://user-images.githubusercontent.com/20526070/73386166-b2e0e200-42ce-11ea-808c-0a511a7e2e25.jpg)
![VLC](https://user-images.githubusercontent.com/20526070/73386169-b3797880-42ce-11ea-919c-fba68f7be3a2.jpg)

**Comment by elelay** [comment]
this explains that ;-)

**Comment by elelay** [comment]
@AntonelloA I've a tentative fix in #752. Can you confirm that it works for you with unpatched mutagen (the fix is to declare the 2 entries -- see dc05734)?

**Comment by AntonelloA** [comment]
@elelay It works! Removed my custom mutagen folder, tried downloading a podcast episode with my old custom tagging.py, and got the error "'subtitle' is not a valid key".
Then replaced tagging.py with the new one in #752 and got no errors, and correct subtitle and comment tags. Great job, thanks!

**Comment by elelay** [comment]
Great! Thanks for the test
