### ISSUE TITLE
I lost all my podcast subscriptions at last update

### ISSUE THREAD

**Issue by jdilena** [gpodder/gpodder#742]
When I did my last update yesterday every subscription of my podcast were lost. I do not find the place whre the subscritptions are stored for using backup

**Comment by auouymous** [comment]
Search for a "gPodder" directory, it is in $HOME on linux. It contains a "Database" file that holds the subscriptions.

**Comment by elelay** [comment]
@jdilena thanks for the report. Do you know what was the old version and the new one?
Also what's your operating system and version?

**Comment by LordLiverpool2** [comment]
Did you upgrade by dumping the portable version into the directory? That's what I did. Turns out that you can't, because the portable version stores its config in a a parallel directory - I assume the binary executable is different. So it's reading a empty database. If so, just use the installer. It will find the proper database.

**Comment by elelay** [comment]
gpodder-portable stores all its data in the config directory.
To update, extract the new version of gpodder-portable to a new directory and move the old config folder in place of the new one.
