### ISSUE TITLE
Converting podcasts to mp3

### ISSUE THREAD

**Issue by memelaser** [gpodder/gpodder#750]
I have several feeds that use several different formats (mainly aac and m4a,) but I need them to all be mp3. I've found and tried to enable the auto-converter extension, but I get the error saying "Requires one of the following commands: avconv, ffmpeg." I have FFMpeg installed AND it is in PATH, and running ffmpeg works in cmd.

**Comment by auouymous** [comment]
Are you able to edit gpodder's files? Around line 1220 in util.py is the find_command function that checks path, search for "def find_command". You can try adding the line below before the `for path ...` line and see if it dumps the path in console. If it doesn't, it means there was no PATH found in the evnironment. Otherwise check if ffpmeg's path is in the path it displays.

The four spaces at start of line are important, don't use a tab.

```
    print(os.environ['PATH'])
```

**Comment by memelaser** [comment]
It dumped my current PATH variable, and ffmpeg is installed in C:\Windows\System32, so it seems very strange that gPodder doesn't see it...

```
C:\Users\Louis\AppData\Local\Programs\Python\Python38;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\QuickTime\QTSystem\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\nodejs\;C:\Program Files\PuTTY\;C:\Users\Louis\AppData\Local\Programs\Python\Python38\Scripts;C:\Users\Louis\AppData\Local\Microsoft\WindowsApps;C:\Users\Louis\AppData\Roaming\npm;C:\Users\Louis\AppData\Local\atom\bin;C:\Users\Louis\AppData\Local\Programs\Python\Python38;C:\Users\Louis\AppData\Local\Programs\Python\Python38\Scripts;;C:\Program Files (x86)\gPodder\bin\ 
```
