### ISSUE TITLE
MKV Files Not Properly Renamed

### ISSUE THREAD

**Issue by ChrisMTheMan** [gpodder/gpodder#796]
Using the following GPodder options, MKV files that are downloaded are not renamed properly.

1. Youtube-dl extension is in use with the "bestvideo+bestaudio" option.
2. Rename Episodes extension is in use.

If an MP4 or WEBM file is downloaded, the renaming works properly.  If an MKV file is downloaded it is not renamed and a zero-byte MP4 file is created that *is* properly named.

I don't have example video links available right now but will have them in a day or two.

**Comment by ChrisMTheMan** [comment]
Well, I found examples quicker that I thought I would.

From channel: https://www.youtube.com/channel/UCgKN1WNjAFq16BbLgIqCOaQ
https://www.youtube.com/watch?v=9ic4_h-Zhe8
https://www.youtube.com/watch?v=UcR02kapqsI
https://www.youtube.com/watch?v=Y5PLhWN8g8s

From channel:  https://www.youtube.com/channel/UCMIjEnXruVHtvgSVf6TgfUg
https://www.youtube.com/watch?v=Y5PLhWN8g8s

**Comment by auouymous** [comment]
I don't see an mkv option for those videos, are you trying to rename the mp4/webm file to an mkv?

**Comment by auouymous** [comment]
Oh, bestvideo+bestaudio is choosing mp4 video and webm audio which causes an mkv container to be used.

**Comment by ChrisMTheMan** [comment]
Yes, you are correct.

**Comment by auouymous** [comment]
The rename extension has nothing to do with this. The youtube-dl extension requests the filename from youtube-dl and then incompatible formats are merged into a file with a different extension (mkv). I'm not sure if the youtube-dl extension can be fixed to handle this. But you can fix it locally by not using bestvideo+bestaudio, and instead use "**bestvideo[ext=mp4]+bestaudio[ext=m4a],bestvideo[ext=webm]+bestaudio[ext=webm]**". You can swap those around if you want webm over mp4/m4a.

**Comment by ChrisMTheMan** [comment]
I'm trying your suggestion now.  Thank you!

**Comment by auouymous** [comment]
The youtube-dl extension and gpodder both query the wrong file extension. The MKV issue is only a problem with youtube-dl since gpodder can't merge DASH formats. It seems both always use MP4 for the filename extension, even if the actual extension is MKV, WEBM, or M4A. For video, they both get the mime type correct. For M4A audio, they both use audio/mp4, but the video icon and video player are used (maybe it should be audio/m4a or maybe the MP4 file extension is selecting the icon/player). For WEBM audio, gpodder uses audio/webm and youtube-dl uses video/webm, both use the video icon and video player.

**Comment by ChrisMTheMan** [comment]
The problem appears to be Fixed!  Auouymous, you sure know the software well...

**Comment by auouymous** [comment]
This issue should probably remain open until the underlying problem is fixed. I have youtube patches for bestvideo+bestaudio and audio-only formats that can't be applied until this is resolved (which I am slowly investigating).

**Comment by ChrisMTheMan** [comment]
I'm not opposed to it staying open.

**Comment by elelay** [comment]
We already try [appending youtube-dl returned extension](https://github.com/gpodder/gpodder/blob/master/share/gpodder/extensions/youtube-dl.py#L98) (`mp4`) to our chosen name .partial.
Shall we also try with the `mkv` extension, knowing that merging can result in a mkv container? It seems the easier catch-all solution, since nothing in youtube-dl [result](https://github.com/gpodder/gpodder/files/4599822/res.txt) points to a .mkv file.

**Comment by auouymous** [comment]
I haven't looked at the code yet, but gpodder and youtube-dl extension always only use the .mp4 extension, never mkv, m4a or webm. Gpodder could check for matching files with mp4, m4a and webm extensions as those are the only ones youtube will send to it (it can't merge to get mkv). Does the youtube-dl extension only work for youtube.com, or does it support every site youtube-dl itself supports? If only youtube, it could check for the presence of files with the above extensions. But sites other than youtube.com could return other extensions.

There is clearly a bug in youtube-dl, your text file shows the video and audio formats as mp4 and webm, but the final result is mp4 instead of mkv.

**Comment by elelay** [comment]
ok, so the algo would be: if `xxx.partial` is empty, try `xxx.partial.`{`<youtube_ext>`,`mp4`,`m4a`, `webm`, `mkv`} and stop at the first non empty file, right?

I agree that youtube-dl returning `mkv` extension would simplify this...
