### ISSUE TITLE
windows html entities in shownotes

### ISSUE THREAD

**Issue by ak474-tech** [gpodder/gpodder#807]
![Untitled](https://user-images.githubusercontent.com/65255331/81743235-a65d4f80-94a1-11ea-801c-16b23c21df87.png)

**Comment by auouymous** [comment]
@elelay The description in shownotes contains unprocessed html entities. I am unable to reproduce this in 3.10.15 with text shownotes, using http://borg.qzx.com/test-rss.php.

@ak474-tech Please provide the feed url.

**Comment by ak474-tech** [comment]
web: https://www.rtve.es/alacarta/audios/nuestro-flamenco/
feed: http://www.rtve.es/api/programas/2058/audios.rss

**Comment by auouymous** [comment]
That feed also works fine with text shownotes in 3.10.15.

**Comment by ak474-tech** [comment]
@auouymous I have the same versión, 3.10.15, I dont know... thanks

**Comment by auouymous** [comment]
Can you open preferences, click the edit config button at bottom, search for "shownotes" and uncheck `ui.gtk.html_shownotes`? I don't know if it takes effect immediately or if gpodder must be restarted. But let me know if that fixes the description.

**Comment by ak474-tech** [comment]
@auouymous I uncheck ui.gtk.html_shownotes and I restarted but the problem is not fixed

**Comment by elelay** [comment]
windows only has text shownotes so no effect is normal.
The issue is an outdated podcastparser dependency on windows.
Please download https://raw.githubusercontent.com/gpodder/podcastparser/045b83623921b4592a64a51ed65d78324b85e1b5/podcastparser.py and move it to your gPodder install (maybe C:\Program Files (x86)\gPodder) in the lib\python3.8\site-packages subfolder to get an up-to-date podcastparser. Then refresh the feed and you should get unescaped text in shownotes

**Comment by elelay** [comment]
Or install / extract gPodder from the latest build:
https://ci.appveyor.com/project/elelay/gpodder/builds/33419871/artifacts

**Comment by elelay** [comment]
gPodder 3.10.16 has the fix for windows (and macOS actually)
