### ISSUE TITLE
Only dowloads the latest episodes

### ISSUE THREAD

**Issue by Jason-XII** [gpodder/gpodder#860]
I am using gpodder to dowload all the episodes from talkpython.fm. When the download is complete, I found out that only the latest 25 episodes are downloaded. I tried to let it download again, but it won't work.

**Comment by auouymous** [comment]
Does the feed have more than 25 episodes, and did you increase gpodder's maximum episode limit? If so, what is the feed URL and what version of gpodder are you running?

**Comment by comodoro** [comment]
It's because the site's default RSS offers just the last, looks like indeed 25 episodes. There is link to the full RSS down on the page, https://talkpython.fm/episodes/rss_full_history. However, gPodder for me does not download the entire playlist, only the last 200 episodes, although the aforementioned RSS does contain 290 episodes.

**Comment by elelay** [comment]
thanks for the link. the 200 épisodes limit is configured in preferences.
