### ISSUE TITLE
Could not find gpod (ubuntu)

### ISSUE THREAD

**Issue by lmjst** [gpodder/gpodder#925]
Hi,
Since I ugraded to Ubuntu 18.04.5 I have to launch gpodder via the command line since no icon is present in the menus.
And then it opens but with the following errors:
I have gpodder 3.10.1 (no update available in my package app)
 ```
gpodder
Storing downloads in /media/dd/7d6c753e-c4e0-4f86-9f86-dac37ac218f7/home/dd/gPodder/Downloads/ (GPODDER_DOWNLOAD_DIR is set)
1608389012.035164 [gpodder.sync] WARNING: Could not find gpod
1608389012.177857 [gpodder.extensions] ERROR: Cannot load ubuntu_appindicator from /usr/share/gpodder/extensions/ubuntu_appindicator.py: No module named 'appindicator'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gpodder/extensions.py", line 257, in set_enabled
    self.load_extension()
  File "/usr/lib/python3/dist-packages/gpodder/extensions.py", line 300, in load_extension
    (extension, 'r', imp.PY_SOURCE))
  File "/usr/lib/python3.6/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/share/gpodder/extensions/ubuntu_appindicator.py", line 19, in <module>
    import appindicator
ModuleNotFoundError: No module named 'appindicator'
  File "/usr/lib/python3.6/site.py", line 183
    file=sys.stderr)
        ^
SyntaxError: invalid syntax
1608389012.441312 [gpodder.schema] ERROR: Orphaned episodes found in database
```

Is this just a probleme of path or something else ?

Tha,ks
dd

**Comment by tpikonen** [comment]
The appindicator Python bindings have been updated in an incompatible way, but your gpodder is old and expects the old appindicator module. This is fixed in new gpodder versions, but not in version 3.10.

You need to either upgrade gpodder yourself (run it from the source tree, or make a local install), or find a package source with an up to date version.

**Comment by auouymous** [comment]
You could also try finding appindicator in ~/gPodder/Settings.json and changing `visible` to `False`, or remove the lines from the file. I don't have ubuntu but it would look something like the following, and these three lines would be entirely removed. It may or may not have the comma after the closing `}`, but it doesn't matter, the entire line would be removed either way.

```
    "appindicator": {
      "visible": false
    },
```

However, the extension has `__mandatory_in__ = 'unity'` and it might be required.

If this works and 3.10.1 downloads your feeds then great, but it has a bunch of other issues that have been fixed in newer releases if you should ever encounter them.

**Comment by lmjst** [comment]
OK thanks, I'll try to upgrade gpodder
